(ns datahike.pg.keywords
  "PostgreSQL's SQL keyword table, as `pg_get_keywords()` returns it.

   Generated from `src/include/parser/kwlist.h` in the upstream
   PostgreSQL checkout — the same file `gen_keywordlist.pl` reads — with
   the category codes and descriptions from `pg_get_keywords` in
   `src/backend/utils/adt/misc.c`:

     UNRESERVED_KEYWORD      U  unreserved
     COL_NAME_KEYWORD        C  unreserved (cannot be function or type name)
     TYPE_FUNC_NAME_KEYWORD  T  reserved (can be function or type name)
     RESERVED_KEYWORD        R  reserved

   This is a real catalog function, not a curiosity: pgjdbc's
   `PgDatabaseMetaData.getSQLKeywords()` runs

     select string_agg(word, ',') from pg_catalog.pg_get_keywords()
     where word <> ALL ('{...}'::text[])

   and passes the result through `castNonNull`. With the function
   missing the aggregate answered one NULL row, which raises an
   AssertionError rather than a SQLException — so Hibernate's
   `catch (SQLException)` fallback did not catch it and every
   SessionFactory build failed.")

(def keyword-rows
  "[word catcode barelabel catdesc baredesc], in ASCII order as PG emits."
  [["abort" "U" true "unreserved" "can be bare label"]
   ["absent" "U" true "unreserved" "can be bare label"]
   ["absolute" "U" true "unreserved" "can be bare label"]
   ["access" "U" true "unreserved" "can be bare label"]
   ["action" "U" true "unreserved" "can be bare label"]
   ["add" "U" true "unreserved" "can be bare label"]
   ["admin" "U" true "unreserved" "can be bare label"]
   ["after" "U" true "unreserved" "can be bare label"]
   ["aggregate" "U" true "unreserved" "can be bare label"]
   ["all" "R" true "reserved" "can be bare label"]
   ["also" "U" true "unreserved" "can be bare label"]
   ["alter" "U" true "unreserved" "can be bare label"]
   ["always" "U" true "unreserved" "can be bare label"]
   ["analyse" "R" true "reserved" "can be bare label"]
   ["analyze" "R" true "reserved" "can be bare label"]
   ["and" "R" true "reserved" "can be bare label"]
   ["any" "R" true "reserved" "can be bare label"]
   ["array" "R" false "reserved" "requires AS"]
   ["as" "R" false "reserved" "requires AS"]
   ["asc" "R" true "reserved" "can be bare label"]
   ["asensitive" "U" true "unreserved" "can be bare label"]
   ["assertion" "U" true "unreserved" "can be bare label"]
   ["assignment" "U" true "unreserved" "can be bare label"]
   ["asymmetric" "R" true "reserved" "can be bare label"]
   ["at" "U" true "unreserved" "can be bare label"]
   ["atomic" "U" true "unreserved" "can be bare label"]
   ["attach" "U" true "unreserved" "can be bare label"]
   ["attribute" "U" true "unreserved" "can be bare label"]
   ["authorization" "T" true "reserved (can be function or type name)" "can be bare label"]
   ["backward" "U" true "unreserved" "can be bare label"]
   ["before" "U" true "unreserved" "can be bare label"]
   ["begin" "U" true "unreserved" "can be bare label"]
   ["between" "C" true "unreserved (cannot be function or type name)" "can be bare label"]
   ["bigint" "C" true "unreserved (cannot be function or type name)" "can be bare label"]
   ["binary" "T" true "reserved (can be function or type name)" "can be bare label"]
   ["bit" "C" true "unreserved (cannot be function or type name)" "can be bare label"]
   ["boolean" "C" true "unreserved (cannot be function or type name)" "can be bare label"]
   ["both" "R" true "reserved" "can be bare label"]
   ["breadth" "U" true "unreserved" "can be bare label"]
   ["by" "U" true "unreserved" "can be bare label"]
   ["cache" "U" true "unreserved" "can be bare label"]
   ["call" "U" true "unreserved" "can be bare label"]
   ["called" "U" true "unreserved" "can be bare label"]
   ["cascade" "U" true "unreserved" "can be bare label"]
   ["cascaded" "U" true "unreserved" "can be bare label"]
   ["case" "R" true "reserved" "can be bare label"]
   ["cast" "R" true "reserved" "can be bare label"]
   ["catalog" "U" true "unreserved" "can be bare label"]
   ["chain" "U" true "unreserved" "can be bare label"]
   ["char" "C" false "unreserved (cannot be function or type name)" "requires AS"]
   ["character" "C" false "unreserved (cannot be function or type name)" "requires AS"]
   ["characteristics" "U" true "unreserved" "can be bare label"]
   ["check" "R" true "reserved" "can be bare label"]
   ["checkpoint" "U" true "unreserved" "can be bare label"]
   ["class" "U" true "unreserved" "can be bare label"]
   ["close" "U" true "unreserved" "can be bare label"]
   ["cluster" "U" true "unreserved" "can be bare label"]
   ["coalesce" "C" true "unreserved (cannot be function or type name)" "can be bare label"]
   ["collate" "R" true "reserved" "can be bare label"]
   ["collation" "T" true "reserved (can be function or type name)" "can be bare label"]
   ["column" "R" true "reserved" "can be bare label"]
   ["columns" "U" true "unreserved" "can be bare label"]
   ["comment" "U" true "unreserved" "can be bare label"]
   ["comments" "U" true "unreserved" "can be bare label"]
   ["commit" "U" true "unreserved" "can be bare label"]
   ["committed" "U" true "unreserved" "can be bare label"]
   ["compression" "U" true "unreserved" "can be bare label"]
   ["concurrently" "T" true "reserved (can be function or type name)" "can be bare label"]
   ["conditional" "U" true "unreserved" "can be bare label"]
   ["configuration" "U" true "unreserved" "can be bare label"]
   ["conflict" "U" true "unreserved" "can be bare label"]
   ["connection" "U" true "unreserved" "can be bare label"]
   ["constraint" "R" true "reserved" "can be bare label"]
   ["constraints" "U" true "unreserved" "can be bare label"]
   ["content" "U" true "unreserved" "can be bare label"]
   ["continue" "U" true "unreserved" "can be bare label"]
   ["conversion" "U" true "unreserved" "can be bare label"]
   ["copy" "U" true "unreserved" "can be bare label"]
   ["cost" "U" true "unreserved" "can be bare label"]
   ["create" "R" false "reserved" "requires AS"]
   ["cross" "T" true "reserved (can be function or type name)" "can be bare label"]
   ["csv" "U" true "unreserved" "can be bare label"]
   ["cube" "U" true "unreserved" "can be bare label"]
   ["current" "U" true "unreserved" "can be bare label"]
   ["current_catalog" "R" true "reserved" "can be bare label"]
   ["current_date" "R" true "reserved" "can be bare label"]
   ["current_role" "R" true "reserved" "can be bare label"]
   ["current_schema" "T" true "reserved (can be function or type name)" "can be bare label"]
   ["current_time" "R" true "reserved" "can be bare label"]
   ["current_timestamp" "R" true "reserved" "can be bare label"]
   ["current_user" "R" true "reserved" "can be bare label"]
   ["cursor" "U" true "unreserved" "can be bare label"]
   ["cycle" "U" true "unreserved" "can be bare label"]
   ["data" "U" true "unreserved" "can be bare label"]
   ["database" "U" true "unreserved" "can be bare label"]
   ["day" "U" false "unreserved" "requires AS"]
   ["deallocate" "U" true "unreserved" "can be bare label"]
   ["dec" "C" true "unreserved (cannot be function or type name)" "can be bare label"]
   ["decimal" "C" true "unreserved (cannot be function or type name)" "can be bare label"]
   ["declare" "U" true "unreserved" "can be bare label"]
   ["default" "R" true "reserved" "can be bare label"]
   ["defaults" "U" true "unreserved" "can be bare label"]
   ["deferrable" "R" true "reserved" "can be bare label"]
   ["deferred" "U" true "unreserved" "can be bare label"]
   ["definer" "U" true "unreserved" "can be bare label"]
   ["delete" "U" true "unreserved" "can be bare label"]
   ["delimiter" "U" true "unreserved" "can be bare label"]
   ["delimiters" "U" true "unreserved" "can be bare label"]
   ["depends" "U" true "unreserved" "can be bare label"]
   ["depth" "U" true "unreserved" "can be bare label"]
   ["desc" "R" true "reserved" "can be bare label"]
   ["detach" "U" true "unreserved" "can be bare label"]
   ["dictionary" "U" true "unreserved" "can be bare label"]
   ["disable" "U" true "unreserved" "can be bare label"]
   ["discard" "U" true "unreserved" "can be bare label"]
   ["distinct" "R" true "reserved" "can be bare label"]
   ["do" "R" true "reserved" "can be bare label"]
   ["document" "U" true "unreserved" "can be bare label"]
   ["domain" "U" true "unreserved" "can be bare label"]
   ["double" "U" true "unreserved" "can be bare label"]
   ["drop" "U" true "unreserved" "can be bare label"]
   ["each" "U" true "unreserved" "can be bare label"]
   ["else" "R" true "reserved" "can be bare label"]
   ["empty" "U" true "unreserved" "can be bare label"]
   ["enable" "U" true "unreserved" "can be bare label"]
   ["encoding" "U" true "unreserved" "can be bare label"]
   ["encrypted" "U" true "unreserved" "can be bare label"]
   ["end" "R" true "reserved" "can be bare label"]
   ["enforced" "U" true "unreserved" "can be bare label"]
   ["enum" "U" true "unreserved" "can be bare label"]
   ["error" "U" true "unreserved" "can be bare label"]
   ["escape" "U" true "unreserved" "can be bare label"]
   ["event" "U" true "unreserved" "can be bare label"]
   ["except" "R" false "reserved" "requires AS"]
   ["exclude" "U" true "unreserved" "can be bare label"]
   ["excluding" "U" true "unreserved" "can be bare label"]
   ["exclusive" "U" true "unreserved" "can be bare label"]
   ["execute" "U" true "unreserved" "can be bare label"]
   ["exists" "C" true "unreserved (cannot be function or type name)" "can be bare label"]
   ["explain" "U" true "unreserved" "can be bare label"]
   ["expression" "U" true "unreserved" "can be bare label"]
   ["extension" "U" true "unreserved" "can be bare label"]
   ["external" "U" true "unreserved" "can be bare label"]
   ["extract" "C" true "unreserved (cannot be function or type name)" "can be bare label"]
   ["false" "R" true "reserved" "can be bare label"]
   ["family" "U" true "unreserved" "can be bare label"]
   ["fetch" "R" false "reserved" "requires AS"]
   ["filter" "U" false "unreserved" "requires AS"]
   ["finalize" "U" true "unreserved" "can be bare label"]
   ["first" "U" true "unreserved" "can be bare label"]
   ["float" "C" true "unreserved (cannot be function or type name)" "can be bare label"]
   ["following" "U" true "unreserved" "can be bare label"]
   ["for" "R" false "reserved" "requires AS"]
   ["force" "U" true "unreserved" "can be bare label"]
   ["foreign" "R" true "reserved" "can be bare label"]
   ["format" "U" true "unreserved" "can be bare label"]
   ["forward" "U" true "unreserved" "can be bare label"]
   ["freeze" "T" true "reserved (can be function or type name)" "can be bare label"]
   ["from" "R" false "reserved" "requires AS"]
   ["full" "T" true "reserved (can be function or type name)" "can be bare label"]
   ["function" "U" true "unreserved" "can be bare label"]
   ["functions" "U" true "unreserved" "can be bare label"]
   ["generated" "U" true "unreserved" "can be bare label"]
   ["global" "U" true "unreserved" "can be bare label"]
   ["grant" "R" false "reserved" "requires AS"]
   ["granted" "U" true "unreserved" "can be bare label"]
   ["greatest" "C" true "unreserved (cannot be function or type name)" "can be bare label"]
   ["group" "R" false "reserved" "requires AS"]
   ["grouping" "C" true "unreserved (cannot be function or type name)" "can be bare label"]
   ["groups" "U" true "unreserved" "can be bare label"]
   ["handler" "U" true "unreserved" "can be bare label"]
   ["having" "R" false "reserved" "requires AS"]
   ["header" "U" true "unreserved" "can be bare label"]
   ["hold" "U" true "unreserved" "can be bare label"]
   ["hour" "U" false "unreserved" "requires AS"]
   ["identity" "U" true "unreserved" "can be bare label"]
   ["if" "U" true "unreserved" "can be bare label"]
   ["ignore" "U" false "unreserved" "requires AS"]
   ["ilike" "T" true "reserved (can be function or type name)" "can be bare label"]
   ["immediate" "U" true "unreserved" "can be bare label"]
   ["immutable" "U" true "unreserved" "can be bare label"]
   ["implicit" "U" true "unreserved" "can be bare label"]
   ["import" "U" true "unreserved" "can be bare label"]
   ["in" "R" true "reserved" "can be bare label"]
   ["include" "U" true "unreserved" "can be bare label"]
   ["including" "U" true "unreserved" "can be bare label"]
   ["increment" "U" true "unreserved" "can be bare label"]
   ["indent" "U" true "unreserved" "can be bare label"]
   ["index" "U" true "unreserved" "can be bare label"]
   ["indexes" "U" true "unreserved" "can be bare label"]
   ["inherit" "U" true "unreserved" "can be bare label"]
   ["inherits" "U" true "unreserved" "can be bare label"]
   ["initially" "R" true "reserved" "can be bare label"]
   ["inline" "U" true "unreserved" "can be bare label"]
   ["inner" "T" true "reserved (can be function or type name)" "can be bare label"]
   ["inout" "C" true "unreserved (cannot be function or type name)" "can be bare label"]
   ["input" "U" true "unreserved" "can be bare label"]
   ["insensitive" "U" true "unreserved" "can be bare label"]
   ["insert" "U" true "unreserved" "can be bare label"]
   ["instead" "U" true "unreserved" "can be bare label"]
   ["int" "C" true "unreserved (cannot be function or type name)" "can be bare label"]
   ["integer" "C" true "unreserved (cannot be function or type name)" "can be bare label"]
   ["intersect" "R" false "reserved" "requires AS"]
   ["interval" "C" true "unreserved (cannot be function or type name)" "can be bare label"]
   ["into" "R" false "reserved" "requires AS"]
   ["invoker" "U" true "unreserved" "can be bare label"]
   ["is" "T" true "reserved (can be function or type name)" "can be bare label"]
   ["isnull" "T" false "reserved (can be function or type name)" "requires AS"]
   ["isolation" "U" true "unreserved" "can be bare label"]
   ["join" "T" true "reserved (can be function or type name)" "can be bare label"]
   ["json" "C" true "unreserved (cannot be function or type name)" "can be bare label"]
   ["json_array" "C" true "unreserved (cannot be function or type name)" "can be bare label"]
   ["json_arrayagg" "C" true "unreserved (cannot be function or type name)" "can be bare label"]
   ["json_exists" "C" true "unreserved (cannot be function or type name)" "can be bare label"]
   ["json_object" "C" true "unreserved (cannot be function or type name)" "can be bare label"]
   ["json_objectagg" "C" true "unreserved (cannot be function or type name)" "can be bare label"]
   ["json_query" "C" true "unreserved (cannot be function or type name)" "can be bare label"]
   ["json_scalar" "C" true "unreserved (cannot be function or type name)" "can be bare label"]
   ["json_serialize" "C" true "unreserved (cannot be function or type name)" "can be bare label"]
   ["json_table" "C" true "unreserved (cannot be function or type name)" "can be bare label"]
   ["json_value" "C" true "unreserved (cannot be function or type name)" "can be bare label"]
   ["keep" "U" true "unreserved" "can be bare label"]
   ["key" "U" true "unreserved" "can be bare label"]
   ["keys" "U" true "unreserved" "can be bare label"]
   ["label" "U" true "unreserved" "can be bare label"]
   ["language" "U" true "unreserved" "can be bare label"]
   ["large" "U" true "unreserved" "can be bare label"]
   ["last" "U" true "unreserved" "can be bare label"]
   ["lateral" "R" true "reserved" "can be bare label"]
   ["leading" "R" true "reserved" "can be bare label"]
   ["leakproof" "U" true "unreserved" "can be bare label"]
   ["least" "C" true "unreserved (cannot be function or type name)" "can be bare label"]
   ["left" "T" true "reserved (can be function or type name)" "can be bare label"]
   ["level" "U" true "unreserved" "can be bare label"]
   ["like" "T" true "reserved (can be function or type name)" "can be bare label"]
   ["limit" "R" false "reserved" "requires AS"]
   ["listen" "U" true "unreserved" "can be bare label"]
   ["load" "U" true "unreserved" "can be bare label"]
   ["local" "U" true "unreserved" "can be bare label"]
   ["localtime" "R" true "reserved" "can be bare label"]
   ["localtimestamp" "R" true "reserved" "can be bare label"]
   ["location" "U" true "unreserved" "can be bare label"]
   ["lock" "U" true "unreserved" "can be bare label"]
   ["locked" "U" true "unreserved" "can be bare label"]
   ["logged" "U" true "unreserved" "can be bare label"]
   ["lsn" "U" true "unreserved" "can be bare label"]
   ["mapping" "U" true "unreserved" "can be bare label"]
   ["match" "U" true "unreserved" "can be bare label"]
   ["matched" "U" true "unreserved" "can be bare label"]
   ["materialized" "U" true "unreserved" "can be bare label"]
   ["maxvalue" "U" true "unreserved" "can be bare label"]
   ["merge" "U" true "unreserved" "can be bare label"]
   ["merge_action" "C" true "unreserved (cannot be function or type name)" "can be bare label"]
   ["method" "U" true "unreserved" "can be bare label"]
   ["minute" "U" false "unreserved" "requires AS"]
   ["minvalue" "U" true "unreserved" "can be bare label"]
   ["mode" "U" true "unreserved" "can be bare label"]
   ["month" "U" false "unreserved" "requires AS"]
   ["move" "U" true "unreserved" "can be bare label"]
   ["name" "U" true "unreserved" "can be bare label"]
   ["names" "U" true "unreserved" "can be bare label"]
   ["national" "C" true "unreserved (cannot be function or type name)" "can be bare label"]
   ["natural" "T" true "reserved (can be function or type name)" "can be bare label"]
   ["nchar" "C" true "unreserved (cannot be function or type name)" "can be bare label"]
   ["nested" "U" true "unreserved" "can be bare label"]
   ["new" "U" true "unreserved" "can be bare label"]
   ["next" "U" true "unreserved" "can be bare label"]
   ["nfc" "U" true "unreserved" "can be bare label"]
   ["nfd" "U" true "unreserved" "can be bare label"]
   ["nfkc" "U" true "unreserved" "can be bare label"]
   ["nfkd" "U" true "unreserved" "can be bare label"]
   ["no" "U" true "unreserved" "can be bare label"]
   ["none" "C" true "unreserved (cannot be function or type name)" "can be bare label"]
   ["normalize" "C" true "unreserved (cannot be function or type name)" "can be bare label"]
   ["normalized" "U" true "unreserved" "can be bare label"]
   ["not" "R" true "reserved" "can be bare label"]
   ["nothing" "U" true "unreserved" "can be bare label"]
   ["notify" "U" true "unreserved" "can be bare label"]
   ["notnull" "T" false "reserved (can be function or type name)" "requires AS"]
   ["nowait" "U" true "unreserved" "can be bare label"]
   ["null" "R" true "reserved" "can be bare label"]
   ["nullif" "C" true "unreserved (cannot be function or type name)" "can be bare label"]
   ["nulls" "U" true "unreserved" "can be bare label"]
   ["numeric" "C" true "unreserved (cannot be function or type name)" "can be bare label"]
   ["object" "U" true "unreserved" "can be bare label"]
   ["objects" "U" true "unreserved" "can be bare label"]
   ["of" "U" true "unreserved" "can be bare label"]
   ["off" "U" true "unreserved" "can be bare label"]
   ["offset" "R" false "reserved" "requires AS"]
   ["oids" "U" true "unreserved" "can be bare label"]
   ["old" "U" true "unreserved" "can be bare label"]
   ["omit" "U" true "unreserved" "can be bare label"]
   ["on" "R" false "reserved" "requires AS"]
   ["only" "R" true "reserved" "can be bare label"]
   ["operator" "U" true "unreserved" "can be bare label"]
   ["option" "U" true "unreserved" "can be bare label"]
   ["options" "U" true "unreserved" "can be bare label"]
   ["or" "R" true "reserved" "can be bare label"]
   ["order" "R" false "reserved" "requires AS"]
   ["ordinality" "U" true "unreserved" "can be bare label"]
   ["others" "U" true "unreserved" "can be bare label"]
   ["out" "C" true "unreserved (cannot be function or type name)" "can be bare label"]
   ["outer" "T" true "reserved (can be function or type name)" "can be bare label"]
   ["over" "U" false "unreserved" "requires AS"]
   ["overlaps" "T" false "reserved (can be function or type name)" "requires AS"]
   ["overlay" "C" true "unreserved (cannot be function or type name)" "can be bare label"]
   ["overriding" "U" true "unreserved" "can be bare label"]
   ["owned" "U" true "unreserved" "can be bare label"]
   ["owner" "U" true "unreserved" "can be bare label"]
   ["parallel" "U" true "unreserved" "can be bare label"]
   ["parameter" "U" true "unreserved" "can be bare label"]
   ["parser" "U" true "unreserved" "can be bare label"]
   ["partial" "U" true "unreserved" "can be bare label"]
   ["partition" "U" true "unreserved" "can be bare label"]
   ["partitions" "U" true "unreserved" "can be bare label"]
   ["passing" "U" true "unreserved" "can be bare label"]
   ["password" "U" true "unreserved" "can be bare label"]
   ["path" "U" true "unreserved" "can be bare label"]
   ["period" "U" true "unreserved" "can be bare label"]
   ["placing" "R" true "reserved" "can be bare label"]
   ["plan" "U" true "unreserved" "can be bare label"]
   ["plans" "U" true "unreserved" "can be bare label"]
   ["policy" "U" true "unreserved" "can be bare label"]
   ["position" "C" true "unreserved (cannot be function or type name)" "can be bare label"]
   ["preceding" "U" true "unreserved" "can be bare label"]
   ["precision" "C" false "unreserved (cannot be function or type name)" "requires AS"]
   ["prepare" "U" true "unreserved" "can be bare label"]
   ["prepared" "U" true "unreserved" "can be bare label"]
   ["preserve" "U" true "unreserved" "can be bare label"]
   ["primary" "R" true "reserved" "can be bare label"]
   ["prior" "U" true "unreserved" "can be bare label"]
   ["privileges" "U" true "unreserved" "can be bare label"]
   ["procedural" "U" true "unreserved" "can be bare label"]
   ["procedure" "U" true "unreserved" "can be bare label"]
   ["procedures" "U" true "unreserved" "can be bare label"]
   ["program" "U" true "unreserved" "can be bare label"]
   ["publication" "U" true "unreserved" "can be bare label"]
   ["quote" "U" true "unreserved" "can be bare label"]
   ["quotes" "U" true "unreserved" "can be bare label"]
   ["range" "U" true "unreserved" "can be bare label"]
   ["read" "U" true "unreserved" "can be bare label"]
   ["real" "C" true "unreserved (cannot be function or type name)" "can be bare label"]
   ["reassign" "U" true "unreserved" "can be bare label"]
   ["recursive" "U" true "unreserved" "can be bare label"]
   ["ref" "U" true "unreserved" "can be bare label"]
   ["references" "R" true "reserved" "can be bare label"]
   ["referencing" "U" true "unreserved" "can be bare label"]
   ["refresh" "U" true "unreserved" "can be bare label"]
   ["reindex" "U" true "unreserved" "can be bare label"]
   ["relative" "U" true "unreserved" "can be bare label"]
   ["release" "U" true "unreserved" "can be bare label"]
   ["rename" "U" true "unreserved" "can be bare label"]
   ["repeatable" "U" true "unreserved" "can be bare label"]
   ["replace" "U" true "unreserved" "can be bare label"]
   ["replica" "U" true "unreserved" "can be bare label"]
   ["reset" "U" true "unreserved" "can be bare label"]
   ["respect" "U" false "unreserved" "requires AS"]
   ["restart" "U" true "unreserved" "can be bare label"]
   ["restrict" "U" true "unreserved" "can be bare label"]
   ["return" "U" true "unreserved" "can be bare label"]
   ["returning" "R" false "reserved" "requires AS"]
   ["returns" "U" true "unreserved" "can be bare label"]
   ["revoke" "U" true "unreserved" "can be bare label"]
   ["right" "T" true "reserved (can be function or type name)" "can be bare label"]
   ["role" "U" true "unreserved" "can be bare label"]
   ["rollback" "U" true "unreserved" "can be bare label"]
   ["rollup" "U" true "unreserved" "can be bare label"]
   ["routine" "U" true "unreserved" "can be bare label"]
   ["routines" "U" true "unreserved" "can be bare label"]
   ["row" "C" true "unreserved (cannot be function or type name)" "can be bare label"]
   ["rows" "U" true "unreserved" "can be bare label"]
   ["rule" "U" true "unreserved" "can be bare label"]
   ["savepoint" "U" true "unreserved" "can be bare label"]
   ["scalar" "U" true "unreserved" "can be bare label"]
   ["schema" "U" true "unreserved" "can be bare label"]
   ["schemas" "U" true "unreserved" "can be bare label"]
   ["scroll" "U" true "unreserved" "can be bare label"]
   ["search" "U" true "unreserved" "can be bare label"]
   ["second" "U" false "unreserved" "requires AS"]
   ["security" "U" true "unreserved" "can be bare label"]
   ["select" "R" true "reserved" "can be bare label"]
   ["sequence" "U" true "unreserved" "can be bare label"]
   ["sequences" "U" true "unreserved" "can be bare label"]
   ["serializable" "U" true "unreserved" "can be bare label"]
   ["server" "U" true "unreserved" "can be bare label"]
   ["session" "U" true "unreserved" "can be bare label"]
   ["session_user" "R" true "reserved" "can be bare label"]
   ["set" "U" true "unreserved" "can be bare label"]
   ["setof" "C" true "unreserved (cannot be function or type name)" "can be bare label"]
   ["sets" "U" true "unreserved" "can be bare label"]
   ["share" "U" true "unreserved" "can be bare label"]
   ["show" "U" true "unreserved" "can be bare label"]
   ["similar" "T" true "reserved (can be function or type name)" "can be bare label"]
   ["simple" "U" true "unreserved" "can be bare label"]
   ["skip" "U" true "unreserved" "can be bare label"]
   ["smallint" "C" true "unreserved (cannot be function or type name)" "can be bare label"]
   ["snapshot" "U" true "unreserved" "can be bare label"]
   ["some" "R" true "reserved" "can be bare label"]
   ["source" "U" true "unreserved" "can be bare label"]
   ["split" "U" true "unreserved" "can be bare label"]
   ["sql" "U" true "unreserved" "can be bare label"]
   ["stable" "U" true "unreserved" "can be bare label"]
   ["standalone" "U" true "unreserved" "can be bare label"]
   ["start" "U" true "unreserved" "can be bare label"]
   ["statement" "U" true "unreserved" "can be bare label"]
   ["statistics" "U" true "unreserved" "can be bare label"]
   ["stdin" "U" true "unreserved" "can be bare label"]
   ["stdout" "U" true "unreserved" "can be bare label"]
   ["storage" "U" true "unreserved" "can be bare label"]
   ["stored" "U" true "unreserved" "can be bare label"]
   ["strict" "U" true "unreserved" "can be bare label"]
   ["string" "U" true "unreserved" "can be bare label"]
   ["strip" "U" true "unreserved" "can be bare label"]
   ["subscription" "U" true "unreserved" "can be bare label"]
   ["substring" "C" true "unreserved (cannot be function or type name)" "can be bare label"]
   ["support" "U" true "unreserved" "can be bare label"]
   ["symmetric" "R" true "reserved" "can be bare label"]
   ["sysid" "U" true "unreserved" "can be bare label"]
   ["system" "U" true "unreserved" "can be bare label"]
   ["system_user" "R" true "reserved" "can be bare label"]
   ["table" "R" true "reserved" "can be bare label"]
   ["tables" "U" true "unreserved" "can be bare label"]
   ["tablesample" "T" true "reserved (can be function or type name)" "can be bare label"]
   ["tablespace" "U" true "unreserved" "can be bare label"]
   ["target" "U" true "unreserved" "can be bare label"]
   ["temp" "U" true "unreserved" "can be bare label"]
   ["template" "U" true "unreserved" "can be bare label"]
   ["temporary" "U" true "unreserved" "can be bare label"]
   ["text" "U" true "unreserved" "can be bare label"]
   ["then" "R" true "reserved" "can be bare label"]
   ["ties" "U" true "unreserved" "can be bare label"]
   ["time" "C" true "unreserved (cannot be function or type name)" "can be bare label"]
   ["timestamp" "C" true "unreserved (cannot be function or type name)" "can be bare label"]
   ["to" "R" false "reserved" "requires AS"]
   ["trailing" "R" true "reserved" "can be bare label"]
   ["transaction" "U" true "unreserved" "can be bare label"]
   ["transform" "U" true "unreserved" "can be bare label"]
   ["treat" "C" true "unreserved (cannot be function or type name)" "can be bare label"]
   ["trigger" "U" true "unreserved" "can be bare label"]
   ["trim" "C" true "unreserved (cannot be function or type name)" "can be bare label"]
   ["true" "R" true "reserved" "can be bare label"]
   ["truncate" "U" true "unreserved" "can be bare label"]
   ["trusted" "U" true "unreserved" "can be bare label"]
   ["type" "U" true "unreserved" "can be bare label"]
   ["types" "U" true "unreserved" "can be bare label"]
   ["uescape" "U" true "unreserved" "can be bare label"]
   ["unbounded" "U" true "unreserved" "can be bare label"]
   ["uncommitted" "U" true "unreserved" "can be bare label"]
   ["unconditional" "U" true "unreserved" "can be bare label"]
   ["unencrypted" "U" true "unreserved" "can be bare label"]
   ["union" "R" false "reserved" "requires AS"]
   ["unique" "R" true "reserved" "can be bare label"]
   ["unknown" "U" true "unreserved" "can be bare label"]
   ["unlisten" "U" true "unreserved" "can be bare label"]
   ["unlogged" "U" true "unreserved" "can be bare label"]
   ["until" "U" true "unreserved" "can be bare label"]
   ["update" "U" true "unreserved" "can be bare label"]
   ["user" "R" true "reserved" "can be bare label"]
   ["using" "R" true "reserved" "can be bare label"]
   ["vacuum" "U" true "unreserved" "can be bare label"]
   ["valid" "U" true "unreserved" "can be bare label"]
   ["validate" "U" true "unreserved" "can be bare label"]
   ["validator" "U" true "unreserved" "can be bare label"]
   ["value" "U" true "unreserved" "can be bare label"]
   ["values" "C" true "unreserved (cannot be function or type name)" "can be bare label"]
   ["varchar" "C" true "unreserved (cannot be function or type name)" "can be bare label"]
   ["variadic" "R" true "reserved" "can be bare label"]
   ["varying" "U" false "unreserved" "requires AS"]
   ["verbose" "T" true "reserved (can be function or type name)" "can be bare label"]
   ["version" "U" true "unreserved" "can be bare label"]
   ["view" "U" true "unreserved" "can be bare label"]
   ["views" "U" true "unreserved" "can be bare label"]
   ["virtual" "U" true "unreserved" "can be bare label"]
   ["volatile" "U" true "unreserved" "can be bare label"]
   ["wait" "U" true "unreserved" "can be bare label"]
   ["when" "R" true "reserved" "can be bare label"]
   ["where" "R" false "reserved" "requires AS"]
   ["whitespace" "U" true "unreserved" "can be bare label"]
   ["window" "R" false "reserved" "requires AS"]
   ["with" "R" false "reserved" "requires AS"]
   ["within" "U" false "unreserved" "requires AS"]
   ["without" "U" false "unreserved" "requires AS"]
   ["work" "U" true "unreserved" "can be bare label"]
   ["wrapper" "U" true "unreserved" "can be bare label"]
   ["write" "U" true "unreserved" "can be bare label"]
   ["xml" "U" true "unreserved" "can be bare label"]
   ["xmlattributes" "C" true "unreserved (cannot be function or type name)" "can be bare label"]
   ["xmlconcat" "C" true "unreserved (cannot be function or type name)" "can be bare label"]
   ["xmlelement" "C" true "unreserved (cannot be function or type name)" "can be bare label"]
   ["xmlexists" "C" true "unreserved (cannot be function or type name)" "can be bare label"]
   ["xmlforest" "C" true "unreserved (cannot be function or type name)" "can be bare label"]
   ["xmlnamespaces" "C" true "unreserved (cannot be function or type name)" "can be bare label"]
   ["xmlparse" "C" true "unreserved (cannot be function or type name)" "can be bare label"]
   ["xmlpi" "C" true "unreserved (cannot be function or type name)" "can be bare label"]
   ["xmlroot" "C" true "unreserved (cannot be function or type name)" "can be bare label"]
   ["xmlserialize" "C" true "unreserved (cannot be function or type name)" "can be bare label"]
   ["xmltable" "C" true "unreserved (cannot be function or type name)" "can be bare label"]
   ["year" "U" false "unreserved" "requires AS"]
   ["yes" "U" true "unreserved" "can be bare label"]
   ["zone" "U" true "unreserved" "can be bare label"]])
