(ns datahike.pg.query-fns
  "The functions translated SQL calls by name.

   The translator emits a Datalog clause naming one of these by its qualified
   symbol, `datahike.pg.query-fns/sql-eq?` and so on. Every public var here is
   a pure function of its arguments, and nothing else is public: this
   namespace is the allow-list a query may call, so a function that reads or
   changes process state never belongs here. Catalog SQL functions, volatile
   functions and sequences do not come through here at all -- the translator
   binds them as values, and the handler runs the impure ones after the query.

   `datahike.pg.resolve` turns these vars into the table pg-datahike resolves
   query symbols with."
  (:require [datahike.pg.jsonb :as jsonb]
            [datahike.pg.sql.fns :as fns]))

(def filter-array-agg                    fns/filter-array-agg)
(def filter-array-agg-ordered            fns/filter-array-agg-ordered)
(def filter-array-agg-ordered-desc       fns/filter-array-agg-ordered-desc)
(def filter-avg                          fns/filter-avg)
(def filter-avg-numeric                  fns/filter-avg-numeric)
(def filter-bool-and                     fns/filter-bool-and)
(def filter-corr                         fns/filter-corr)
(def filter-count                        fns/filter-count)
(def filter-count-distinct               fns/filter-count-distinct)
(def filter-enum-max                     fns/filter-enum-max)
(def filter-enum-min                     fns/filter-enum-min)
(def filter-json-agg                     fns/filter-json-agg)
(def filter-json-object-agg              fns/filter-json-object-agg)
(def filter-jsonb-agg                    fns/filter-jsonb-agg)
(def filter-jsonb-object-agg             fns/filter-jsonb-object-agg)
(def filter-max                          fns/filter-max)
(def filter-min                          fns/filter-min)
(def filter-mode                         fns/filter-mode)
(def filter-percentile-cont              fns/filter-percentile-cont)
(def filter-percentile-disc              fns/filter-percentile-disc)
(def filter-stddev-pop                   fns/filter-stddev-pop)
(def filter-stddev-pop-numeric           fns/filter-stddev-pop-numeric)
(def filter-stddev-samp                  fns/filter-stddev-samp)
(def filter-stddev-samp-numeric          fns/filter-stddev-samp-numeric)
(def filter-string-agg                   fns/filter-string-agg)
(def filter-string-agg-ordered           fns/filter-string-agg-ordered)
(def filter-string-agg-ordered-desc      fns/filter-string-agg-ordered-desc)
(def filter-sum                          fns/filter-sum)
(def filter-sum-float4                   fns/filter-sum-float4)
(def filter-sum-numeric                  fns/filter-sum-numeric)
(def filter-variance-pop                 fns/filter-variance-pop)
(def filter-variance-pop-numeric         fns/filter-variance-pop-numeric)
(def filter-variance-samp                fns/filter-variance-samp)
(def filter-variance-samp-numeric        fns/filter-variance-samp-numeric)
(def jsonb-eq?                           jsonb/jsonb-eq?)
(def jsonb-ne?                           jsonb/jsonb-ne?)
(def sql-*                               fns/sql-*)
(def sql-+                               fns/sql-+)
(def sql--                               fns/sql--)
(def sql-and3                            fns/sql-and3)
(def sql-at-time-zone                    fns/sql-at-time-zone)
(def sql-between3?                       fns/sql-between3?)
(def sql-between?                        fns/sql-between?)
(def sql-bit-and                         fns/sql-bit-and)
(def sql-bit-not                         fns/sql-bit-not)
(def sql-bit-or                          fns/sql-bit-or)
(def sql-bit-shift-left                  fns/sql-bit-shift-left)
(def sql-bit-shift-right                 fns/sql-bit-shift-right)
(def sql-bit-xor                         fns/sql-bit-xor)
(def sql-btrim                           fns/sql-btrim)
(def sql-date+                           fns/sql-date+)
(def sql-date-                           fns/sql-date-)
(def sql-distinct?                       fns/sql-distinct?)
(def sql-div                             fns/sql-div)
(def sql-eq3?                            fns/sql-eq3?)
(def sql-eq?                             fns/sql-eq?)
(def sql-extract                         fns/sql-extract)
(def sql-f4*                             fns/sql-f4*)
(def sql-f4+                             fns/sql-f4+)
(def sql-f4-                             fns/sql-f4-)
(def sql-f4div                           fns/sql-f4div)
(def sql-ge3?                            fns/sql-ge3?)
(def sql-ge?                             fns/sql-ge?)
(def sql-gt3?                            fns/sql-gt3?)
(def sql-gt?                             fns/sql-gt?)
(def sql-in3?                            fns/sql-in3?)
(def sql-in?                             fns/sql-in?)
(def sql-int*                            fns/sql-int*)
(def sql-int+                            fns/sql-int+)
(def sql-int-                            fns/sql-int-)
(def sql-int-div                         fns/sql-int-div)
(def sql-int-neg                         fns/sql-int-neg)
(def sql-le3?                            fns/sql-le3?)
(def sql-le?                             fns/sql-le?)
(def sql-like3?                          fns/sql-like3?)
(def sql-lt3?                            fns/sql-lt3?)
(def sql-lt?                             fns/sql-lt?)
(def sql-ltrim                           fns/sql-ltrim)
(def sql-may?                            fns/sql-may?)
(def sql-mod                             fns/sql-mod)
(def sql-money*                          fns/sql-money*)
(def sql-money+                          fns/sql-money+)
(def sql-money-                          fns/sql-money-)
(def sql-money-div                       fns/sql-money-div)
(def sql-money-div-money                 fns/sql-money-div-money)
(def sql-ne3?                            fns/sql-ne3?)
(def sql-ne?                             fns/sql-ne?)
(def sql-not-between?                    fns/sql-not-between?)
(def sql-not-distinct?                   fns/sql-not-distinct?)
(def sql-not-null?                       fns/sql-not-null?)
(def sql-not3                            fns/sql-not3)
(def sql-null?                           fns/sql-null?)
(def sql-or3                             fns/sql-or3)
(def sql-power-op                        fns/sql-power-op)
(def sql-rtrim                           fns/sql-rtrim)
(def sql-substring                       fns/sql-substring)
(def sql-time-                           fns/sql-time-)
(def sql-timestamp-                      fns/sql-timestamp-)
(def sql-unsupported-temporal-arithmetic fns/sql-unsupported-temporal-arithmetic)
