(ns datahike.pg.sql.ddl
  "DDL translation: CREATE TABLE, CREATE SEQUENCE, constraint extraction.

   Produces Datahike tx-data that installs schema attributes (`:db/ident`,
   `:db/valueType`, `:db/cardinality`, `:db/unique`, `:pg/type`, and the
   pgwire-specific `:pg/*` constraint metadata).

   The predicate helpers (`identity-column?`, `column-is-primary-key?`,
   `column-is-unique?`, `column-is-not-null?`, `specs-contain-seq?`,
   `column-check-expr-text`, `column-default-spec`) walk JSqlParser's
   `ColumnDefinition.getColumnSpecs` lists, which are raw strings — so
   each predicate is a case-insensitive token matcher.

   Entry points:
     - translate-create-table    — main; returns {:type :ddl :tx-data [...]}
     - translate-create-sequence — CREATE SEQUENCE name [...]

   Helpers:
     - extract-ddl-constraints — CHECK / NOT NULL / UNIQUE / FK clauses
     - extract-inherits        — PostgreSQL INHERITS"
  (:require [clojure.string :as str]
            [datahike.pg.jsonb :as jb]
            [datahike.pg.schema :as pgs]
            [datahike.pg.sql.params :as params]
            [datahike.pg.types :as types])
  (:import [net.sf.jsqlparser.schema Column Table]
           [net.sf.jsqlparser.expression StringValue]
           [net.sf.jsqlparser.statement.create.table
            CreateTable ColumnDefinition ColDataType Index
            CheckConstraint ForeignKeyIndex]
           [net.sf.jsqlparser.statement.create.sequence CreateSequence]))

(set! *warn-on-reflection* true)

;; DDL type mapping delegates to centralized registry
(def ^:private pg-type->dh-type types/sql-name->dh-type)

(def ^:private serial-types
  "SQL type names that imply auto-increment (like IDENTITY)."
  #{"serial" "serial2" "serial4" "serial8" "bigserial" "smallserial"})

(defn identity-column?
  "Check if a JSqlParser ColumnDefinition has GENERATED BY DEFAULT AS IDENTITY
   or uses a SERIAL type (which implies auto-increment)."
  [^ColumnDefinition col]
  (or
   ;; SERIAL/BIGSERIAL type
   (let [^ColDataType cdt (.getColDataType col)]
     (when cdt
       (contains? serial-types (str/lower-case (str (.getDataType cdt))))))
   ;; GENERATED BY DEFAULT AS IDENTITY spec
   (let [specs (.getColumnSpecs col)]
     (when (seq specs)
       (some #(= "identity" (str/lower-case (str %))) specs)))))

(defn specs-contain-seq?
  "True when the whitespace-split column-spec list contains the given token
   sequence contiguously, case-insensitive. Used to detect PRIMARY KEY
   (two tokens) and UNIQUE (one token) inline on a ColumnDefinition."
  [specs tokens]
  (let [lowered (mapv #(str/lower-case (str %)) specs)
        needle  (mapv str/lower-case tokens)
        n       (count needle)]
    (when (and (pos? n) (<= n (count lowered)))
      (boolean
       (some (fn [i] (= needle (subvec lowered i (+ i n))))
             (range (inc (- (count lowered) n))))))))

(defn column-is-primary-key?
  "True when a column has inline PRIMARY KEY in its column specs."
  [^ColumnDefinition col]
  (when-let [specs (.getColumnSpecs col)]
    (specs-contain-seq? specs ["primary" "key"])))

(defn column-is-unique?
  "True when a column has inline UNIQUE in its column specs (not part of
   PRIMARY KEY, which we handle separately)."
  [^ColumnDefinition col]
  (when-let [specs (.getColumnSpecs col)]
    (and (specs-contain-seq? specs ["unique"])
         (not (column-is-primary-key? col)))))

(defn column-is-not-null?
  "True when the column-spec list carries `NOT NULL`. PK columns are
   implicitly NOT NULL in PG; callers should combine this with
   column-is-primary-key? to avoid double-flagging."
  [^ColumnDefinition col]
  (when-let [specs (.getColumnSpecs col)]
    (specs-contain-seq? specs ["not" "null"])))

(defn column-check-expr-text
  "Extract the text of an inline `CHECK (…)` constraint from a
   ColumnDefinition's ColumnSpecs, or nil if none.

   JSqlParser emits inline CHECK as two tokens: `CHECK` and a second
   token that's the entire parenthesized expression, e.g.
   `[\"CHECK\" \"(x > 0)\"]`. We keep the inner text.

   Also tolerate the tokenized form PG dialect dumps sometimes
   produce — CHECK followed by `(`, individual tokens, `)` — by
   paren-matching across the remaining specs."
  [^ColumnDefinition col]
  (when-let [specs (.getColumnSpecs col)]
    (let [lowered (mapv #(str/lower-case (str %)) specs)
          originals (mapv str specs)
          idx (.indexOf ^java.util.List lowered "check")]
      (when (and (>= idx 0) (< (inc idx) (count lowered)))
        (let [nxt (nth originals (inc idx))]
          (cond
            ;; Single-token case: `(x > 0)` or `(x > 0) NOT NULL` etc.
            (and (str/starts-with? nxt "(")
                 (str/ends-with? nxt ")"))
            (str/trim (subs nxt 1 (dec (count nxt))))
            ;; Single token but partial paren (very rare) — walk forward.
            (str/starts-with? nxt "(")
            (let [concat-rest (str/join " " (subvec originals (inc idx)))
                  idx2 (.indexOf ^String concat-rest (int \())]
              (when (>= idx2 0)
                (let [after (subs concat-rest (inc idx2))
                      ;; paren-matched substring up to matching ).
                      matched
                      (loop [i 0 depth 1 sb (StringBuilder.)]
                        (cond
                          (or (>= i (count after)) (zero? depth)) (str sb)
                          (= \( (.charAt ^String after i))
                          (do (.append sb (.charAt ^String after i))
                              (recur (inc i) (inc depth) sb))
                          (= \) (.charAt ^String after i))
                          (if (= 1 depth)
                            (str sb)
                            (do (.append sb (.charAt ^String after i))
                                (recur (inc i) (dec depth) sb)))
                          :else
                          (do (.append sb (.charAt ^String after i))
                              (recur (inc i) depth sb))))]
                  (str/trim matched))))))))))

(defn column-default-spec
  "If the column spec list carries `DEFAULT <expr>`, return a map
   describing the default so translate-create-table can attach it to
   the schema entity. Shape:

     {:kind :literal  :value <long|double|string|boolean|nil>}
     {:kind :fn       :value <canonical fn name string>}
     {:kind :nextval  :value <sequence name string>}
     {:kind :unsupported :raw <original SQL text>}

   The literal branch handles numbers, single-quoted strings, boolean
   keywords, and NULL. The :fn branch covers the stateless current-*
   functions PG users rely on. :nextval is the only stateful default
   we support and it ties into our existing sequence infrastructure.
   Unknown expressions land in :unsupported so CREATE TABLE can
   raise loudly instead of silently dropping the constraint.

   Walks the ColumnSpecs as whitespace-separated tokens; tolerant of
   parens (e.g. `DEFAULT (now())`)."
  [^ColumnDefinition col]
  (when-let [specs (.getColumnSpecs col)]
    (let [lowered (mapv #(str/lower-case (str %)) specs)
          originals (mapv str specs)
          idx (.indexOf ^java.util.List lowered "default")]
      (when (and (>= idx 0) (< (inc idx) (count lowered)))
        (let [;; Grab tokens up to the next reserved word — NOT,
              ;; CHECK, UNIQUE, PRIMARY, REFERENCES — or end.
              stop? #{"not" "check" "unique" "primary" "references"
                      "generated" "collate"}
              toks (loop [i (inc idx) acc []]
                     (if (or (>= i (count lowered)) (stop? (nth lowered i)))
                       acc
                       (recur (inc i) (conj acc (nth originals i)))))
              raw (str/trim (str/join " " toks))
              ;; Peel outer parens so `DEFAULT (0)` works identically
              ;; to `DEFAULT 0`.
              peeled (if (and (str/starts-with? raw "(")
                              (str/ends-with? raw ")"))
                       (str/trim (subs raw 1 (dec (count raw))))
                       raw)
              low (str/lower-case peeled)
              strip-cast (fn [s]
                           ;; Strip a trailing `::typename` so
                           ;; `0::int` and `'x'::text` parse as the
                           ;; inner literal. We record the value
                           ;; itself; coerce-insert-value adapts it
                           ;; to the column type at INSERT time.
                           (str/replace s #"\s*::\s*[a-zA-Z_][\w ]*(?:\([^)]*\))?\s*$" ""))
              ;; JSqlParser tokenizes `now()` as ["now" "()"] which
              ;; joins to "now ()" — collapse whitespace between the
              ;; identifier and the parens so the fn-name regex
              ;; below matches regardless of tokenization.
              collapse-fn-parens #(str/replace %
                                               #"([A-Za-z_][A-Za-z0-9_]*)\s*\(\s*\)"
                                               "$1()")
              base (-> peeled strip-cast collapse-fn-parens)]
          (cond
            (= low "null")  {:kind :literal :value nil}
            (= low "true")  {:kind :literal :value true}
            (= low "false") {:kind :literal :value false}
            ;; Number literal (possibly signed, decimal).
            (re-matches #"-?\d+(?:\.\d+)?" base)
            {:kind :literal
             :value (if (str/includes? base ".")
                      (Double/parseDouble base)
                      (Long/parseLong base))}
            ;; Single-quoted string. PG doubles embedded ' as ''; keep
            ;; that for parity with StringValue literals elsewhere.
            (re-matches #"'(?:[^']|'')*'" base)
            {:kind :literal
             :value (-> base (subs 1 (dec (count base)))
                        (str/replace "''" "'"))}
            ;; Known zero-arg functions. Match either form: `now`,
            ;; `now()`, `current_timestamp`, `CURRENT_TIMESTAMP`. Also
            ;; accept the AT TIME ZONE wrapper Odoo uses
            ;; (`now() AT TIME ZONE 'UTC'`) — for our `:db.type/instant`
            ;; columns the timezone wrapper is a no-op since we don't
            ;; track per-column timezone offsets, so it folds into
            ;; plain `now`.
            (re-matches #"(?i)(?:now|current_timestamp|statement_timestamp|transaction_timestamp|clock_timestamp)(?:\(\))?(?:\s+at\s+time\s+zone\s+'[^']+')?"
                        base)
            {:kind :fn :value "now"}
            (re-matches #"(?i)current_date(?:\(\))?" base)
            {:kind :fn :value "current_date"}
            (re-matches #"(?i)current_time(?:\(\))?" base)
            {:kind :fn :value "current_time"}
            (re-matches #"(?i)current_user(?:\(\))?|session_user(?:\(\))?|user"
                        base)
            {:kind :fn :value "current_user"}
            ;; nextval('seqname') — literal arg.
            (re-matches #"(?i)nextval\s*\(\s*'([^']+)'\s*\)" base)
            (let [m (re-matches #"(?i)nextval\s*\(\s*'([^']+)'\s*\)" base)]
              {:kind :nextval :value (second m)})
            :else
            {:kind :unsupported :raw raw}))))))

(defn extract-ddl-constraints
  "Collect PRIMARY KEY and UNIQUE constraints from a CreateTable into a
   normalized shape. Merges column-level specs (`id INT PRIMARY KEY`) with
   table-level indexes (`PRIMARY KEY (a,b), UNIQUE (c)`).

   Returns a map:
     :pk-cols       — vector of column names in the PK (empty if none)
     :pk-name       — explicit constraint name for the PK, or nil
     :uniques       — vector of {:cols [str...] :name str-or-nil}
                      each an independent UNIQUE constraint
   Column names are the raw SQL idents (unquoted), not namespaced keywords.
   The caller owns the :t/col namespace mapping."
  [^CreateTable ct]
  (let [columns (or (.getColumnDefinitions ct) [])
        ;; Column-level PRIMARY KEY / UNIQUE specs
        col-pk-cols (vec (keep (fn [^ColumnDefinition col]
                                 (when (column-is-primary-key? col)
                                   (params/unquote-ident (.getColumnName col))))
                               columns))
        col-unique-cols (vec (keep (fn [^ColumnDefinition col]
                                     (when (column-is-unique? col)
                                       (params/unquote-ident (.getColumnName col))))
                                   columns))
        ;; Table-level indexes: PRIMARY KEY (…), UNIQUE (…), CONSTRAINT n UNIQUE (…)
        indexes (or (.getIndexes ct) [])
        index-pk (first (filter (fn [^Index idx]
                                  (= "PRIMARY KEY" (.getType idx)))
                                indexes))
        index-pk-cols (when index-pk
                        (mapv (comp params/unquote-ident str)
                              (.getColumns ^Index index-pk)))
        index-pk-name (when index-pk (.getName ^Index index-pk))
        index-uniques (vec (keep (fn [^Index idx]
                                   (when (= "UNIQUE" (.getType idx))
                                     {:cols (mapv (comp params/unquote-ident str)
                                                  (.getColumns idx))
                                      :name (.getName idx)}))
                                 indexes))
        ;; Table-level CHECK constraints — `CheckConstraint` extends
        ;; Index, so they ride along in .getIndexes. Keep the original
        ;; expression as a string; enforcement re-parses it.
        table-checks (vec (keep (fn [^Index idx]
                                  (when (instance? CheckConstraint idx)
                                    {:name (.getName ^CheckConstraint idx)
                                     :expr (str (.getExpression ^CheckConstraint idx))}))
                                indexes))
        ;; Column-level CHECK: `col INT CHECK (…)` — extract from the
        ;; ColumnSpecs text.
        col-checks (vec (keep (fn [^ColumnDefinition col]
                                (when-let [et (column-check-expr-text col)]
                                  {:name nil
                                   :col (params/unquote-ident (.getColumnName col))
                                   :expr et}))
                              columns))
        ;; Table-level FOREIGN KEY — ForeignKeyIndex is also an Index.
        table-fks (vec (keep (fn [^Index idx]
                               (when (instance? ForeignKeyIndex idx)
                                 (let [^ForeignKeyIndex fk idx
                                       cols (mapv (comp params/unquote-ident str)
                                                  (.getColumnsNames fk))
                                       ref-tbl (some-> (.getTable fk) .getName params/unquote-ident)
                                       ref-cols (mapv (comp params/unquote-ident str)
                                                      (or (.getReferencedColumnNames fk) []))]
                                   {:name (.getName fk)
                                    :cols cols
                                    :parent-table ref-tbl
                                    :parent-cols ref-cols
                                    :on-delete (some-> (.getOnDeleteReferenceOption fk)
                                                       str/lower-case)
                                    :on-update (some-> (.getOnUpdateReferenceOption fk)
                                                       str/lower-case)})))
                             indexes))]
    {:pk-cols  (or (not-empty index-pk-cols) col-pk-cols)
     :pk-name  index-pk-name
     :uniques  (into (mapv (fn [c] {:cols [c] :name nil}) col-unique-cols)
                     index-uniques)
     :checks   (into col-checks table-checks)
     :fks      table-fks}))

(defn extract-inherits
  "Extract parent table name from INHERITS clause in CREATE TABLE options."
  [^CreateTable ct]
  (when-let [opts (.getTableOptionsStrings ct)]
    (let [opts-vec (vec opts)
          idx (.indexOf ^java.util.List opts-vec "INHERITS")]
      (when (and (>= idx 0) (< (inc idx) (count opts-vec)))
        ;; Next element is "(parent_table)" — strip parens
        (let [raw (str (nth opts-vec (inc idx)))]
          (-> raw
              (str/replace #"^\(" "")
              (str/replace #"\)$" "")
              str/trim))))))

(defn translate-create-table
  "Translate a CREATE TABLE statement to Datahike schema transaction data.
   Also returns :table-name, :column-order, :identity-cols, and :inherits."
  [^CreateTable ct db]
  (let [table (.getTable ct)
        table-name (params/unquote-ident (.getName ^Table table))
        ns table-name
        columns (.getColumnDefinitions ct)
        ;; Detect INHERITS (parent_table) — either from this CREATE TABLE
        ;; directly, or from prior registration (some clients issue CREATE
        ;; TABLE twice: once with INHERITS, then again with the full column
        ;; list without INHERITS — both refer to the same child table).
        parent-from-sql (extract-inherits ct)
        parent-from-db (when db
                         (ffirst ((requiring-resolve 'datahike.api/q)
                                  '{:find [?p]
                                    :where [[?e :__inherit__/child ?c]
                                            [?e :__inherit__/parent ?p]]
                                    :in [$ ?c]}
                                  db table-name)))
        parent-table (or parent-from-sql parent-from-db)
        ;; For INHERITS children, skip `id` — it's shared with parent. Adding
        ;; a child-namespaced id attr would cause auto-increment to assign
        ;; DIFFERENT values for child vs parent, breaking SELECT FROM parent
        ;; WHERE id = N lookups.
        skip-col? (fn [cn]
                    (or (= cn "db_id")
                        (and parent-table (= cn "id"))))
        col-names (vec (keep (fn [^ColumnDefinition col]
                               (let [cn (params/unquote-ident (.getColumnName col))]
                                 (when-not (skip-col? cn) cn)))
                             columns))
        ;; Detect IDENTITY columns and create implicit sequences
        identity-cols (vec (keep (fn [^ColumnDefinition col]
                                   (let [cn (params/unquote-ident (.getColumnName col))]
                                     (when (and (identity-column? col)
                                                (not (skip-col? cn)))
                                       cn)))
                                 columns))
        ;; Extract PRIMARY KEY + UNIQUE from DDL. The Datahike schema
        ;; mapping is deliberately asymmetric to respect both worlds:
        ;;   single-col PRIMARY KEY → :db.unique/identity
        ;;     (Datomic upsert semantics for Datalog callers; the SQL
        ;;      layer adds a pre-check in translate-insert to raise
        ;;      23505 for bare INSERT collisions.)
        ;;   single-col UNIQUE     → :db.unique/value
        ;;     (Datahike enforces strict uniqueness natively; 23505
        ;;      falls out via :db.error/unique → errors.clj mapping.)
        ;;   multi-col  PRIMARY KEY / UNIQUE → additional :db.type/tuple
        ;;     attr with :db/tupleAttrs pointing at the components, same
        ;;     uniqueness as the single-col case.
        constraints (extract-ddl-constraints ct)
        pk-cols (:pk-cols constraints)
        single-pk? (= 1 (count pk-cols))
        single-pk-col (when single-pk? (first pk-cols))
        pk-cols-set (set pk-cols)
        ;; UNIQUE columns that aren't ALSO the single-col PK (avoid
        ;; double-constraining a single column — PG would reject the
        ;; redundant declaration, we silently dedupe).
        single-unique-cols (into #{}
                                 (comp (filter (comp #(= 1 (count %)) :cols))
                                       (map (comp first :cols))
                                       (remove pk-cols-set))
                                 (:uniques constraints))
        ;; Multi-col PK / UNIQUE — emit a derived tuple attr per
        ;; constraint. The ident name MUST NOT begin with '_' —
        ;; Datahike treats any name starting with underscore as a
        ;; reverse-ref shorthand (Datomic convention) and strips the
        ;; leading _ during attr validation, which then fails to
        ;; resolve. Using `pg$` as a prefix keeps the attrs
        ;; distinguishable from user columns without tripping that
        ;; detection.
        multi-pk-tuple (when (and (seq pk-cols) (> (count pk-cols) 1))
                         {:ident     (keyword ns "pg$pk_tuple")
                          :tuple-cols pk-cols
                          :unique    :db.unique/identity
                          :name      (or (:pk-name constraints)
                                         (str table-name "_pkey"))})
        multi-uniques (vec
                       (keep-indexed
                        (fn [i {:keys [cols name]}]
                          (when (> (count cols) 1)
                            {:ident     (keyword ns (str "pg$unique_tuple_" i))
                             :tuple-cols cols
                             :unique    :db.unique/value
                             :name      (or name
                                            (str table-name "_"
                                                 (str/join "_" cols) "_key"))}))
                        (:uniques constraints)))
        tuple-attrs (into (if multi-pk-tuple [multi-pk-tuple] [])
                          multi-uniques)
        ;; Allocate a stable PG OID for this table and attach it to the
        ;; row-marker entity. Used by pg_class.oid / pg_attribute.attrelid
        ;; so pgjdbc's field-metadata JOIN can resolve column names.
        ;; Persists with the schema (file-backed databases keep OIDs
        ;; across restarts; :memory dies with the db). Skip when the
        ;; row-marker already carries one — CREATE TABLE IF NOT EXISTS
        ;; re-runs the schema tx, and Datahike rejects changing a
        ;; cardinality/one attr that's already set on an entity.
        table-oid-val (when (and db (nil? (pgs/table-oid db table-name)))
                        (pgs/next-table-oid db))
        ;; Schema tx-data for columns
        schema-tx (into
                   [(cond-> {:db/ident       (pgs/row-marker-attr table-name)
                             :db/valueType   :db.type/boolean
                             :db/cardinality :db.cardinality/one}
                      table-oid-val (assoc :pg/table-oid table-oid-val))]
                   (for [^ColumnDefinition col columns
                         :let [col-name (params/unquote-ident (.getColumnName col))
                               ^ColDataType cdt (.getColDataType col)
                               raw-type (str/lower-case (str (.getDataType cdt)))
                               base-type (str/replace raw-type #"\s*\([^)]*\)" "")
                               ;; Detect array column. JSqlParser exposes
                               ;; the array dimensions via getArrayData()
                               ;; — a list whose size = ndim (entries are
                               ;; null for unsized `[]`, integers for
                               ;; sized `[3]` which PG ignores anyway).
                               ;; We look up the element-keyword from
                               ;; `base-type` (typmod stripped) — which
                               ;; for `numeric(10,2)[]` resolves to
                               ;; `:numeric`, matching PG's array OIDs.
                               array-data (try (.getArrayData cdt)
                                               (catch Throwable _ nil))
                               ndim       (when (seq array-data) (count array-data))
                               array-spec (when ndim
                                            (when-let [elem (get types/sql-name->elem-kw base-type)]
                                              {:elem    elem
                                               :pg-name (str "_" (name elem))
                                               :ndim    ndim}))
                               ;; Array columns: store as serialized
                               ;; canonical text in :db.type/string.
                               ;; Round-trip via to-pg-text/from-pg-text.
                               dh-type (cond
                                         array-spec :db.type/string
                                         :else (or (get pg-type->dh-type raw-type)
                                                   (get pg-type->dh-type base-type)
                                                   :db.type/string))
                               ;; NUMERIC(p, s): preserve precision +
                               ;; scale via PG's atttypmod encoding so
                               ;; clients see the declared type. Real
                               ;; PG keeps these in pg_attribute; we
                               ;; tag the schema attr's ident entity
                               ;; with `:pg/typmod` and surface it in
                               ;; the catalog + describeResult. Skipped
                               ;; for array columns — we don't currently
                               ;; preserve element typmod through the
                               ;; serialized array codec.
                               numeric-typmod
                               (when (and (= dh-type :db.type/bigdec) (not array-spec))
                                 (let [[p s] (types/parse-numeric-args raw-type)]
                                   (when (or p s)
                                     (types/encode-numeric-typmod p s))))
                               pk-here? (or (and single-pk-col (= col-name single-pk-col))
                                            (contains? pk-cols-set col-name))
                               ;; NOT NULL inline; PK is implicitly NOT NULL
                               ;; but we avoid redundant flagging so the
                               ;; enforcement path doesn't double-error.
                               not-null-here? (and (not pk-here?)
                                                   (column-is-not-null? col))
                               default-spec (column-default-spec col)
                               _ (when (= :unsupported (:kind default-spec))
                                   (throw (ex-info "DEFAULT expression not supported"
                                                   {:error :feature-not-supported
                                                    :feature (str "DEFAULT expression " (pr-str (:raw default-spec))
                                                                  " on column \"" col-name "\"")
                                                    :detail (str "DEFAULT expression " (pr-str (:raw default-spec))
                                                                 " on column \"" col-name "\" is not supported"
                                                                 " — only literals, now(), current_date,"
                                                                 " current_time, current_user, and"
                                                                 " nextval('seq') are implemented")
                                                    :column col-name})))]
                         :when (not (skip-col? col-name))]
                     (cond-> {:db/ident       (keyword ns col-name)
                              :db/valueType   dh-type
                              :db/cardinality :db.cardinality/one}
                       ;; Array column: tag with element-keyword and ndim
                       ;; so coerce-insert-value / value->string /
                       ;; coerce-pg-array can reconstruct the typed
                       ;; PgArray from the stored canonical text. The
                       ;; `:pg/type "_T"` slot drives column-OID
                       ;; resolution via pg-name->oid in oid_infer.
                       array-spec (assoc :pg/type        (:pg-name array-spec)
                                         :pg/array-elem  (:elem array-spec)
                                         ;; Long-cast for Datahike's
                                         ;; :db.type/long validation
                                         ;; (count returns int).
                                         :pg/array-ndim  (long (:ndim array-spec)))
                       numeric-typmod (assoc :pg/typmod numeric-typmod)
                       not-null-here? (assoc :pg/not-null true)
                       (and default-spec
                            (not= :unsupported (:kind default-spec)))
                       (as-> m
                             (cond-> m
                               true (assoc :pg/default-kind (:kind default-spec))
                               (some? (:value default-spec))
                               (assoc :pg/default-value (str (:value default-spec)))
                               (= :nextval (:kind default-spec))
                               (assoc :pg/default-arg (:value default-spec))))
                       ;; Track original SQL type when the Datahike
                       ;; valueType isn't a 1:1 mapping. jsonb/json
                       ;; both reduce to :db.type/string; date/time/
                       ;; timestamp all collapse to :db.type/instant.
                       ;; Without this hint, ParameterDescription
                       ;; advertises a DATE param as `timestamp`
                       ;; (OID 1114) and pgjdbc rejects subsequent
                       ;; setDate binds with "Can't change resolved
                       ;; type for param …".
                       (#{"jsonb" "json"
                          "date" "time" "timestamp"
                          "timestamptz" "timestamp without time zone"
                          "timestamp with time zone"
                          "time without time zone"
                          "time with time zone"} base-type)
                       (assoc :pg/type
                              (cond
                                (#{"timestamp without time zone"} base-type) "timestamp"
                                (#{"timestamp with time zone"} base-type)    "timestamptz"
                                (#{"time without time zone"
                                   "time with time zone"} base-type) "time"
                                :else base-type))
                       ;; Single-col PRIMARY KEY → upsert identity.
                       (and single-pk-col (= col-name single-pk-col))
                       (assoc :db/unique :db.unique/identity)
                       ;; Single-col UNIQUE (non-PK) → strict value.
                       (contains? single-unique-cols col-name)
                       (assoc :db/unique :db.unique/value))))
        ;; Derived tuple attrs for multi-col PK / UNIQUE constraints.
        tuple-schema-tx (mapv (fn [{:keys [ident tuple-cols unique]}]
                                {:db/ident       ident
                                 :db/valueType   :db.type/tuple
                                 :db/tupleAttrs  (mapv #(keyword ns %) tuple-cols)
                                 :db/cardinality :db.cardinality/one
                                 :db/unique      unique})
                              tuple-attrs)
        schema-tx (into schema-tx tuple-schema-tx)
        ;; CHECK-constraint entities. One per CHECK clause, named
        ;; deterministically so CREATE TABLE IF NOT EXISTS is
        ;; idempotent (:pg/check-name carries :db.unique/identity).
        check-entities
        (vec (for [[i {:keys [name col expr]}] (map-indexed vector (:checks constraints))
                   :let [cname (or name
                                   (if col
                                     (str table-name "_" col "_check")
                                     (str table-name "_check_" i)))]]
               {:pg/check-name  cname
                :pg/check-table table-name
                :pg/check-expr  expr}))
        ;; FK-constraint entities. Column lists stored as
        ;; JSON-serialized strings for order-preserving round-trip.
        fk-entities
        (vec (for [[i {:keys [name cols parent-table parent-cols on-delete on-update]}]
                   (map-indexed vector (:fks constraints))
                   :let [cname (or name
                                   (str table-name "_"
                                        (str/join "_" cols) "_fkey"))
                         ->action (fn [s]
                                    (when s
                                      (case (str/lower-case s)
                                        "cascade"     :cascade
                                        "set null"    :set-null
                                        "set default" :set-default
                                        "restrict"    :restrict
                                        "no action"   :no-action
                                        :no-action)))
                         od (->action on-delete)
                         ou (->action on-update)]
                   :when parent-table]
               (cond-> {:pg/fk-name         cname
                        :pg/fk-child-table  table-name
                        :pg/fk-child-cols   (jb/serialize-jsonb cols)
                        :pg/fk-parent-table parent-table
                        :pg/fk-parent-cols  (jb/serialize-jsonb parent-cols)}
                 od (assoc :pg/fk-on-delete od)
                 ou (assoc :pg/fk-on-update ou))))
        schema-tx (into schema-tx (into check-entities fk-entities))
        ;; Loud error at DDL for FK actions we don't yet implement.
        ;; ON DELETE CASCADE *is* implemented (server.clj
        ;; collect-fk-cascade-retractions!) so we accept it here.
        ;; ON DELETE SET NULL / SET DEFAULT and ON UPDATE * still raise.
        _ (doseq [fk fk-entities]
            (when (contains? #{:set-null :set-default}
                             (:pg/fk-on-delete fk))
              (throw (ex-info "ON DELETE action not supported"
                              {:error :feature-not-supported
                               :feature (str "FOREIGN KEY ON DELETE "
                                             (name (:pg/fk-on-delete fk)))
                               :detail (str "FOREIGN KEY ON DELETE "
                                            (name (:pg/fk-on-delete fk))
                                            " is not yet supported for "
                                            (:pg/fk-name fk)
                                            " — only NO ACTION / RESTRICT / CASCADE are enforced")
                               :constraint (:pg/fk-name fk)})))
            (when (contains? #{:cascade :set-null :set-default}
                             (:pg/fk-on-update fk))
              (throw (ex-info "ON UPDATE action not supported"
                              {:error :feature-not-supported
                               :feature (str "FOREIGN KEY ON UPDATE "
                                             (name (:pg/fk-on-update fk)))
                               :detail (str "FOREIGN KEY ON UPDATE "
                                            (name (:pg/fk-on-update fk))
                                            " is not yet supported for "
                                            (:pg/fk-name fk))
                               :constraint (:pg/fk-name fk)}))))
        ;; Sequence schema + initial entity for each IDENTITY column
        seq-tx (vec (mapcat (fn [col-name]
                              (let [seq-name (str table-name "_" col-name "_seq")]
                                [{:db/ident :__seq__/name :db/valueType :db.type/string
                                  :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
                                 {:db/ident :__seq__/value :db/valueType :db.type/long
                                  :db/cardinality :db.cardinality/one}
                                 {:db/ident :__seq__/increment :db/valueType :db.type/long
                                  :db/cardinality :db.cardinality/one}
                                 {:__seq__/name seq-name :__seq__/value 0 :__seq__/increment 1}]))
                            identity-cols))]
    (cond-> {:type :ddl-create
             :table-name table-name
             :if-not-exists? (.isIfNotExists ct)
             :column-order col-names
             :identity-cols identity-cols
             :pk-cols pk-cols
             :pk-name (or (:pk-name constraints)
                          (when (seq pk-cols) (str table-name "_pkey")))
             :unique-cols (vec single-unique-cols)
             :tx-data (into schema-tx seq-tx)}
      parent-table (assoc :inherits parent-table))))

;; ============================================================================
;; Sequence DDL translation
;; ============================================================================

(defn translate-create-sequence
  "Translate CREATE SEQUENCE to Datahike schema + initial entity.
   Sequences are stored as entities with :__seq__/* attributes."
  [^CreateSequence cs]
  (let [seq-name (str (.getName (.getSequence cs)))
        ;; Parse options: START WITH, INCREMENT BY
        full-sql (str cs)
        lower (str/lower-case full-sql)
        start-val (or (when-let [m (re-find #"start\s+with\s+(\d+)" lower)]
                        (Long/parseLong (second m)))
                      1)
        increment (or (when-let [m (re-find #"increment\s+by\s+(\d+)" lower)]
                        (Long/parseLong (second m)))
                      1)]
    {:type :ddl-create-sequence
     :seq-name seq-name
     :tx-data
     [;; Schema attributes for sequences (idempotent — already exist after first CREATE)
      {:db/ident :__seq__/name :db/valueType :db.type/string
       :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
      {:db/ident :__seq__/value :db/valueType :db.type/long
       :db/cardinality :db.cardinality/one}
      {:db/ident :__seq__/increment :db/valueType :db.type/long
       :db/cardinality :db.cardinality/one}
      ;; The sequence entity itself.
      ;; PG semantics: `CREATE SEQUENCE s START WITH N` means the
      ;; first `nextval('s')` returns N. handle-nextval is
      ;; advance-then-return (reads :__seq__/value, writes value+inc,
      ;; returns value+inc), so we initialise the stored value to
      ;; `start-val - increment` — the first advance lands on
      ;; start-val. The IDENTITY-column path (translate-create-table
      ;; line ~635) follows the same convention with `:__seq__/value
      ;; 0` for `START WITH 1, INCREMENT BY 1`.
      {:__seq__/name seq-name
       :__seq__/value (- start-val increment)
       :__seq__/increment increment}]}))
