(ns datahike.pg.sql.ddl
  "DDL translation: CREATE TABLE, CREATE SEQUENCE, constraint extraction.

   Produces Datahike tx-data that installs schema attributes (`:db/ident`,
   `:db/valueType`, `:db/cardinality`, `:db/unique`, `:pg/type`, and the
   pgwire-specific `:pg/*` constraint metadata).

   The predicate helpers (`identity-column?`, `column-is-primary-key?`,
   `column-is-unique?`, `column-is-not-null?`, `specs-contain-seq?`,
   `column-check-expr-text`, `column-default-spec`) walk JSqlParser's
   `ColumnDefinition.getColumnSpecs` lists, which are raw strings — so
   each predicate is a case-insensitive token matcher.

   Entry points:
     - translate-create-table    — main; returns {:type :ddl :tx-data [...]}
     - translate-create-sequence — CREATE SEQUENCE name [...]

   Helpers:
     - extract-ddl-constraints — CHECK / NOT NULL / UNIQUE / FK clauses
     - extract-inherits        — PostgreSQL INHERITS"
  (:require [clojure.set :as set]
            [clojure.string :as str]
            [datahike.api :as d]
            [datahike.pg.errors :as errors]
            [datahike.pg.jsonb :as jb]
            [datahike.pg.schema :as pgs]
            [datahike.pg.sql.params :as params]
            [datahike.pg.types :as types]
            [datahike.pg.vector :as pg-vector])
  (:import [net.sf.jsqlparser.schema Column Table]
           [net.sf.jsqlparser.expression StringValue]
           [net.sf.jsqlparser.statement.create.table
            CreateTable ColumnDefinition ColDataType Index
            CheckConstraint ForeignKeyIndex]
           [net.sf.jsqlparser.statement.create.sequence CreateSequence]))

(set! *warn-on-reflection* true)

;; DDL type mapping delegates to centralized registry
(def ^:private pg-type->dh-type types/sql-name->dh-type)

(def ^:private serial-types
  "SQL type names that imply auto-increment (like IDENTITY)."
  #{"serial" "serial2" "serial4" "serial8" "bigserial" "smallserial"})

(defn- primary-key-cols
  "Return the declared primary-key columns of `table-name` in key order.

   PostgreSQL permits `REFERENCES parent` without an explicit column list;
   that shorthand targets the parent's primary key.  Datahike represents a
   single-column key directly and a composite key through our hidden
   `pg$pk_tuple` attribute, so recover both shapes here while translating the
   child DDL."
  [db table-name]
  (when db
    (let [schema (:schema db)
          tuple-props (get schema (keyword table-name "pg$pk_tuple"))]
      (if (seq (:db/tupleAttrs tuple-props))
        (mapv name (:db/tupleAttrs tuple-props))
        (when-let [attr
                   (some (fn [[a props]]
                           (when (and (keyword? a)
                                      (= table-name (namespace a))
                                      (= :db.unique/identity (:db/unique props))
                                      (not= "pg$pk_tuple" (name a)))
                             a))
                         schema)]
          [(name attr)])))))

(defn- attr-enum-name
  "Return the enum type attached to a persisted column attribute."
  [db attr]
  (when db
    (ffirst
     (d/q '{:find [?name]
            :in [$ ?ident]
            :where [[?e :db/ident ?ident]
                    [?e :datahike.pg/enum-of ?name]]}
          db attr))))

(defn identity-column?
  "Check if a JSqlParser ColumnDefinition has GENERATED BY DEFAULT AS IDENTITY
   or uses a SERIAL type (which implies auto-increment)."
  [^ColumnDefinition col]
  (or
   ;; SERIAL/BIGSERIAL type
   (let [^ColDataType cdt (.getColDataType col)]
     (when cdt
       (contains? serial-types (str/lower-case (str (.getDataType cdt))))))
   ;; GENERATED BY DEFAULT AS IDENTITY spec
   (let [specs (.getColumnSpecs col)]
     (when (seq specs)
       (some #(= "identity" (str/lower-case (str %))) specs)))))

(defn specs-contain-seq?
  "True when the whitespace-split column-spec list contains the given token
   sequence contiguously, case-insensitive. Used to detect PRIMARY KEY
   (two tokens) and UNIQUE (one token) inline on a ColumnDefinition."
  [specs tokens]
  (let [lowered (mapv #(str/lower-case (str %)) specs)
        needle  (mapv str/lower-case tokens)
        n       (count needle)]
    (when (and (pos? n) (<= n (count lowered)))
      (boolean
       (some (fn [i] (= needle (subvec lowered i (+ i n))))
             (range (inc (- (count lowered) n))))))))

(defn column-is-primary-key?
  "True when a column has inline PRIMARY KEY in its column specs."
  [^ColumnDefinition col]
  (when-let [specs (.getColumnSpecs col)]
    (specs-contain-seq? specs ["primary" "key"])))

(defn column-is-unique?
  "True when a column has inline UNIQUE in its column specs (not part of
   PRIMARY KEY, which we handle separately)."
  [^ColumnDefinition col]
  (when-let [specs (.getColumnSpecs col)]
    (and (specs-contain-seq? specs ["unique"])
         (not (column-is-primary-key? col)))))

(defn column-is-not-null?
  "True when the column-spec list carries `NOT NULL`. PK columns are
   implicitly NOT NULL in PG; callers should combine this with
   column-is-primary-key? to avoid double-flagging."
  [^ColumnDefinition col]
  (when-let [specs (.getColumnSpecs col)]
    (specs-contain-seq? specs ["not" "null"])))

(defn column-check-expr-text
  "Extract the text of an inline `CHECK (…)` constraint from a
   ColumnDefinition's ColumnSpecs, or nil if none.

   JSqlParser emits inline CHECK as two tokens: `CHECK` and a second
   token that's the entire parenthesized expression, e.g.
   `[\"CHECK\" \"(x > 0)\"]`. We keep the inner text.

   Also tolerate the tokenized form PG dialect dumps sometimes
   produce — CHECK followed by `(`, individual tokens, `)` — by
   paren-matching across the remaining specs."
  [^ColumnDefinition col]
  (when-let [specs (.getColumnSpecs col)]
    (let [lowered (mapv #(str/lower-case (str %)) specs)
          originals (mapv str specs)
          idx (.indexOf ^java.util.List lowered "check")]
      (when (and (>= idx 0) (< (inc idx) (count lowered)))
        (let [nxt (nth originals (inc idx))]
          (cond
            ;; Single-token case: `(x > 0)` or `(x > 0) NOT NULL` etc.
            (and (str/starts-with? nxt "(")
                 (str/ends-with? nxt ")"))
            (str/trim (subs nxt 1 (dec (count nxt))))
            ;; Single token but partial paren (very rare) — walk forward.
            (str/starts-with? nxt "(")
            (let [concat-rest (str/join " " (subvec originals (inc idx)))
                  idx2 (.indexOf ^String concat-rest (int \())]
              (when (>= idx2 0)
                (let [after (subs concat-rest (inc idx2))
                      ;; paren-matched substring up to matching ).
                      matched
                      (loop [i 0 depth 1 sb (StringBuilder.)]
                        (cond
                          (or (>= i (count after)) (zero? depth)) (str sb)
                          (= \( (.charAt ^String after i))
                          (do (.append sb (.charAt ^String after i))
                              (recur (inc i) (inc depth) sb))
                          (= \) (.charAt ^String after i))
                          (if (= 1 depth)
                            (str sb)
                            (do (.append sb (.charAt ^String after i))
                                (recur (inc i) (dec depth) sb)))
                          :else
                          (do (.append sb (.charAt ^String after i))
                              (recur (inc i) depth sb))))]
                  (str/trim matched))))))))))

(defn column-default-spec
  "If the column spec list carries `DEFAULT <expr>`, return a map
   describing the default so translate-create-table can attach it to
   the schema entity. Shape:

     {:kind :literal  :value <long|double|string|boolean|nil>}
     {:kind :bit      :value <canonical bit input string>}
     {:kind :bit-coerced :value <quoted input coerced to a bit column>}
     {:kind :fn       :value <canonical fn name string>}
     {:kind :nextval  :value <sequence name string>}
     {:kind :unsupported :raw <original SQL text>}

   The literal branch handles numbers, single-quoted strings, boolean
   keywords, and NULL. The :bit branch prevents a digit-only bit default
   from being reinterpreted as a number by delayed materialization. The
   :fn branch covers the stateless current-*
   functions PG users rely on. :nextval is the only stateful default
   we support and it ties into our existing sequence infrastructure.
   Unknown expressions land in :unsupported so CREATE TABLE can
   raise loudly instead of silently dropping the constraint.

   Walks the ColumnSpecs as whitespace-separated tokens; tolerant of
   parens (e.g. `DEFAULT (now())`)."
  [^ColumnDefinition col]
  (when-let [specs (.getColumnSpecs col)]
    (let [lowered (mapv #(str/lower-case (str %)) specs)
          originals (mapv str specs)
          idx (.indexOf ^java.util.List lowered "default")]
      (when (and (>= idx 0) (< (inc idx) (count lowered)))
        (let [;; Grab tokens up to the next reserved word — NOT,
              ;; CHECK, UNIQUE, PRIMARY, REFERENCES — or end.
              stop? #{"not" "check" "unique" "primary" "references"
                      "generated" "collate"}
              toks (loop [i (inc idx) acc []]
                     (if (or (>= i (count lowered)) (stop? (nth lowered i)))
                       acc
                       (recur (inc i) (conj acc (nth originals i)))))
              raw (str/trim (str/join " " toks))
              ;; Peel outer parens so `DEFAULT (0)` works identically
              ;; to `DEFAULT 0`.
              peeled (if (and (str/starts-with? raw "(")
                              (str/ends-with? raw ")"))
                       (str/trim (subs raw 1 (dec (count raw))))
                       raw)
              low (str/lower-case peeled)
              strip-cast (fn [s]
                           ;; Strip a trailing `::typename` so
                           ;; `0::int`, `'x'::text`, and pg_dump's
                           ;; `'G'::public.mpaa_rating` (cast to a
                           ;; schema-qualified custom type) all
                           ;; parse as the inner literal. We record
                           ;; the value itself; coerce-insert-value
                           ;; adapts it to the column type at INSERT
                           ;; time.
                           (str/replace s #"\s*::\s*[a-zA-Z_][\w. ]*(?:\([^)]*\))?\s*$" ""))
              ;; JSqlParser tokenizes `now()` as ["now" "()"] which
              ;; joins to "now ()" — collapse whitespace between the
              ;; identifier and the parens so the fn-name regex
              ;; below matches regardless of tokenization.
              collapse-fn-parens #(str/replace %
                                               #"([A-Za-z_][A-Za-z0-9_]*)\s*\(\s*\)"
                                               "$1()")
              base (-> peeled strip-cast collapse-fn-parens)]
          (cond
            (= low "null")  {:kind :literal :value nil}
            (= low "true")  {:kind :literal :value true}
            (= low "false") {:kind :literal :value false}
            ;; Number literal (possibly signed, decimal).
            (re-matches #"-?\d+(?:\.\d+)?" base)
            {:kind :literal
             :value (if (str/includes? base ".")
                      (Double/parseDouble base)
                      (Long/parseLong base))}
            ;; Single-quoted string. PG doubles embedded ' as ''; keep
            ;; that for parity with StringValue literals elsewhere.
            (re-matches #"'(?:[^']|'')*'" base)
            {:kind :literal
             :value (-> base (subs 1 (dec (count base)))
                        (str/replace "''" "'"))}
            ;; SQL-standard bit literal.  Defaults are materialized after
            ;; INSERT expression coercion, so persist the canonical digit
            ;; run used by bit/varbit columns. Hex keeps its input prefix so
            ;; the column's bit coercion can expand each digit to four bits.
            (re-matches #"(?i)b'[01]*'" base)
            {:kind :bit :value (subs base 2 (dec (count base)))}
            (re-matches #"(?i)x'[0-9a-f]*'" base)
            {:kind :bit
             :value (str "x" (subs base 2 (dec (count base))))}
            ;; Known zero-arg functions. Match either form: `now`,
            ;; `now()`, `current_timestamp`, `CURRENT_TIMESTAMP`. Also
            ;; accept the AT TIME ZONE wrapper Odoo uses
            ;; (`now() AT TIME ZONE 'UTC'`) — for our `:db.type/instant`
            ;; columns the timezone wrapper is a no-op since we don't
            ;; track per-column timezone offsets, so it folds into
            ;; plain `now`.
            (re-matches #"(?i)(?:now|current_timestamp|statement_timestamp|transaction_timestamp|clock_timestamp)(?:\(\))?(?:\s+at\s+time\s+zone\s+'[^']+')?"
                        base)
            {:kind :fn :value "now"}
            (re-matches #"(?i)current_date(?:\(\))?" base)
            {:kind :fn :value "current_date"}
            (re-matches #"(?i)current_time(?:\(\))?" base)
            {:kind :fn :value "current_time"}
            (re-matches #"(?i)current_user(?:\(\))?|session_user(?:\(\))?|user"
                        base)
            {:kind :fn :value "current_user"}
            ;; nextval('seqname') — literal arg. Also accepts:
            ;;   - schema-qualified seq names: nextval('public.foo_id_seq')
            ;;     (we drop the schema; sequences live in a flat namespace)
            ;;   - the ::regclass cast that pg_dump always emits:
            ;;     nextval('foo_seq'::regclass)
            ;;   - parens preserved by our DEFAULT-paren rewrite rule:
            ;;     (nextval('foo_seq'::regclass))
            (re-matches #"(?i)\(?\s*nextval\s*\(\s*'(?:[^'.]+\.)?([^']+)'\s*(?:::\s*regclass)?\s*\)\s*\)?" base)
            (let [m (re-matches #"(?i)\(?\s*nextval\s*\(\s*'(?:[^'.]+\.)?([^']+)'\s*(?:::\s*regclass)?\s*\)\s*\)?" base)]
              {:kind :nextval :value (second m)})
            :else
            {:kind :unsupported :raw raw}))))))

(defn extract-ddl-constraints
  "Collect PRIMARY KEY and UNIQUE constraints from a CreateTable into a
   normalized shape. Merges column-level specs (`id INT PRIMARY KEY`) with
   table-level indexes (`PRIMARY KEY (a,b), UNIQUE (c)`).

   Returns a map:
     :pk-cols       — vector of column names in the PK (empty if none)
     :pk-name       — explicit constraint name for the PK, or nil
     :uniques       — vector of {:cols [str...] :name str-or-nil}
                      each an independent UNIQUE constraint
   Column names are the raw SQL idents (unquoted), not namespaced keywords.
   The caller owns the :t/col namespace mapping."
  [^CreateTable ct]
  (let [columns (or (.getColumnDefinitions ct) [])
        ;; Column-level PRIMARY KEY / UNIQUE specs
        col-pk-cols (vec (keep (fn [^ColumnDefinition col]
                                 (when (column-is-primary-key? col)
                                   (params/unquote-ident (.getColumnName col))))
                               columns))
        col-unique-cols (vec (keep (fn [^ColumnDefinition col]
                                     (when (column-is-unique? col)
                                       (params/unquote-ident (.getColumnName col))))
                                   columns))
        ;; Table-level indexes: PRIMARY KEY (…), UNIQUE (…), CONSTRAINT n UNIQUE (…)
        indexes (or (.getIndexes ct) [])
        index-pk (first (filter (fn [^Index idx]
                                  (= "PRIMARY KEY" (.getType idx)))
                                indexes))
        index-pk-cols (when index-pk
                        (mapv (comp params/unquote-ident str)
                              (.getColumns ^Index index-pk)))
        index-pk-name (when index-pk
                        (params/unquote-ident (.getName ^Index index-pk)))
        index-uniques (vec (keep (fn [^Index idx]
                                   (when (= "UNIQUE" (.getType idx))
                                     {:cols (mapv (comp params/unquote-ident str)
                                                  (.getColumns idx))
                                      :name (some-> (.getName idx) params/unquote-ident)}))
                                 indexes))
        ;; Table-level CHECK constraints — `CheckConstraint` extends
        ;; Index, so they ride along in .getIndexes. Keep the original
        ;; expression as a string; enforcement re-parses it.
        table-checks (vec (keep (fn [^Index idx]
                                  (when (instance? CheckConstraint idx)
                                    {:name (some-> (.getName ^CheckConstraint idx)
                                                   params/unquote-ident)
                                     :expr (str (.getExpression ^CheckConstraint idx))}))
                                indexes))
        ;; Column-level CHECK: `col INT CHECK (…)` — extract from the
        ;; ColumnSpecs text.
        col-checks (vec (keep (fn [^ColumnDefinition col]
                                (when-let [et (column-check-expr-text col)]
                                  {:name nil
                                   :col (params/unquote-ident (.getColumnName col))
                                   :expr et}))
                              columns))
        ;; Table-level FOREIGN KEY — ForeignKeyIndex is also an Index.
        table-fks (vec (keep (fn [^Index idx]
                               (when (instance? ForeignKeyIndex idx)
                                 (let [^ForeignKeyIndex fk idx
                                       cols (mapv (comp params/unquote-ident str)
                                                  (.getColumnsNames fk))
                                       ref-tbl (some-> (.getTable fk) .getName params/unquote-ident)
                                       parsed-ref-cols
                                       (mapv (comp params/unquote-ident str)
                                             (or (.getReferencedColumnNames fk) []))
                                       ref-cols (if (= ["__pg_default_pk__"] parsed-ref-cols)
                                                  []
                                                  parsed-ref-cols)]
                                   {:name (some-> (.getName fk) params/unquote-ident)
                                    :cols cols
                                    :parent-table ref-tbl
                                    :parent-cols ref-cols
                                    :on-delete (some-> (.getOnDeleteReferenceOption fk)
                                                       str/lower-case)
                                    :on-update (some-> (.getOnUpdateReferenceOption fk)
                                                       str/lower-case)})))
                             indexes))]
    {:pk-cols  (or (not-empty index-pk-cols) col-pk-cols)
     :pk-name  index-pk-name
     :uniques  (into (mapv (fn [c] {:cols [c] :name nil}) col-unique-cols)
                     index-uniques)
     :checks   (into col-checks table-checks)
     :fks      table-fks}))

(defn extract-inherits
  "Extract parent table name from INHERITS clause in CREATE TABLE options."
  [^CreateTable ct]
  (when-let [opts (.getTableOptionsStrings ct)]
    (let [opts-vec (vec opts)
          idx (.indexOf ^java.util.List opts-vec "INHERITS")]
      (when (and (>= idx 0) (< (inc idx) (count opts-vec)))
        ;; Next element is "(parent_table)" — strip parens
        (let [raw (str (nth opts-vec (inc idx)))]
          (-> raw
              (str/replace #"^\(" "")
              (str/replace #"\)$" "")
              str/trim))))))

(defn pg-type-hint
  "The `:pg/type` a column of SQL type `base-type` should record, or nil
   when the storage valueType already implies the right OID.

   Datahike collapses whole families onto one carrier — every integer is
   :db.type/long, every temporal is :db.type/instant, jsonb and bit are
   :db.type/string — so this hint is the ONLY thing that lets the
   catalog report `date` rather than `timestamp`, or `int4` rather than
   `int8`. Drivers pick codecs off those OIDs.

   Extracted so `ALTER TABLE ... ADD COLUMN` records the same hints
   CREATE TABLE does. It previously recorded them only for json/jsonb,
   so a column added by ALTER as `date` or `smallint` reported the
   storage type forever after.

   `array?` suppresses the scalar hints: an `int[]` column has base-type
   \"int\" too and its array `:pg/type` (\"_int4\") is set elsewhere."
  [^String base-type array?]
  (let [bt (some-> base-type str/lower-case str/trim)]
    (cond
      (nil? bt) nil

      array? nil

      (#{"jsonb" "json" "money" "interval" "tsvector" "tsquery" "vector"} bt) bt

      (#{"date" "time" "timestamp" "timestamptz"
         "timestamp without time zone" "timestamp with time zone"
         "time without time zone" "time with time zone"} bt)
      (cond
        (= "timestamp without time zone" bt) "timestamp"
        (= "timestamp with time zone" bt)    "timestamptz"
        (= "time without time zone" bt) "time"
        (= "time with time zone" bt)    "timetz"
        :else bt)

      (#{:bit :varbit} (types/cast-category bt))
      (if (= :varbit (types/cast-category bt)) "varbit" "bit")

      (#{"smallint" "int2" "smallserial" "serial2"} bt) "int2"
      (#{"integer" "int" "int4" "serial" "serial4"} bt) "int4"
      (= "oid" bt) "oid"
      :else nil)))

(defn translate-create-table
  "Translate a CREATE TABLE statement to Datahike schema transaction data.
   Also returns :table-name, :column-order, :identity-cols, and :inherits."
  [^CreateTable ct db]
  (let [table (.getTable ct)
        table-name (params/unquote-ident (.getName ^Table table))
        ns table-name
        ;; CREATE [GLOBAL|LOCAL] TEMP[ORARY] TABLE — JSqlParser keeps the
        ;; leading keywords in getCreateOptionsStrings. We track temp
        ;; tables per session and drop them when the connection closes
        ;; (see make-query-handler's :temp-tables / close). Not full
        ;; per-session isolation — Datahike has one shared schema, so a
        ;; temp table is visible to other live connections and concurrent
        ;; CREATEs of the same name still collide — but it matches PG's
        ;; default session lifetime for the sequential single-connection
        ;; usage the conformance suites exercise.
        temp? (boolean (some #(#{"temp" "temporary"} (str/lower-case %))
                             (.getCreateOptionsStrings ct)))
        columns (.getColumnDefinitions ct)
        ;; Detect INHERITS (parent_table) — either from this CREATE TABLE
        ;; directly, or from prior registration (some clients issue CREATE
        ;; TABLE twice: once with INHERITS, then again with the full column
        ;; list without INHERITS — both refer to the same child table).
        parent-from-sql (extract-inherits ct)
        parent-from-db (when db
                         (ffirst (d/q
                                  '{:find [?p]
                                    :where [[?e :__inherit__/child ?c]
                                            [?e :__inherit__/parent ?p]]
                                    :in [$ ?c]}
                                  db table-name)))
        parent-table (or parent-from-sql parent-from-db)
        ;; JSqlParser exposes the whole `INHERITS (p1, p2)` list as one
        ;; option string. pg-datahike's inheritance model remains
        ;; single-parent, but the regression fixture deliberately creates a
        ;; multiple-parent table whose own column is still useful. Validate
        ;; every named parent without treating the comma-joined spelling as
        ;; one relation.
        missing-parent (when (and parent-from-sql db)
                         (some (fn [parent]
                                 (let [parent (str/trim parent)]
                                   (when (nil? (pgs/column-info
                                                (:schema db) parent db))
                                     parent)))
                               (str/split parent-from-sql #",")))
        _ (when missing-parent
            (throw (errors/pg-error :undefined-table {:table missing-parent})))
        vector-columns
        (into #{}
              (keep (fn [^ColumnDefinition col]
                      (let [^ColDataType cdt (.getColDataType col)
                            base (types/normalize-sql-type-name
                                  (str (.getDataType cdt)))]
                        (when (= :vector (types/cast-category base))
                          (params/unquote-ident (.getColumnName col))))))
              columns)
        _vector-arrays
        (doseq [^ColumnDefinition col columns
                :let [^ColDataType cdt (.getColDataType col)
                      raw-type (str (.getDataType cdt))
                      base (types/normalize-sql-type-name
                            raw-type)
                      array-data (try (.getArrayData cdt)
                                      (catch Throwable _ nil))]]
          (when (and (types/vector-type-spelling? raw-type)
                     (not= :vector (types/cast-category base)))
            (throw (errors/pg-error
                    :undefined-object
                    {:kind "type" :name raw-type})))
          (when (and (seq array-data)
                     (= :vector (types/cast-category base)))
            (throw (errors/pg-error
                    :feature-not-supported
                    {:message "vector arrays are not supported"}))))
        ;; For INHERITS children, skip `id` — it's shared with parent. Adding
        ;; a child-namespaced id attr would cause auto-increment to assign
        ;; DIFFERENT values for child vs parent, breaking SELECT FROM parent
        ;; WHERE id = N lookups.
        skip-col? (fn [cn]
                    (or (= cn "db_id")
                        (and parent-table (= cn "id"))))
        col-names (vec (keep (fn [^ColumnDefinition col]
                               (let [cn (params/unquote-ident (.getColumnName col))]
                                 (when-not (skip-col? cn) cn)))
                             columns))
        ;; Detect IDENTITY columns and create implicit sequences
        identity-cols (vec (keep (fn [^ColumnDefinition col]
                                   (let [cn (params/unquote-ident (.getColumnName col))]
                                     (when (and (identity-column? col)
                                                (not (skip-col? cn)))
                                       cn)))
                                 columns))
        ;; Extract PRIMARY KEY + UNIQUE from DDL. The Datahike schema
        ;; mapping is deliberately asymmetric to respect both worlds:
        ;;   single-col PRIMARY KEY → :db.unique/identity
        ;;     (Datomic upsert semantics for Datalog callers; the SQL
        ;;      layer adds a pre-check in translate-insert to raise
        ;;      23505 for bare INSERT collisions.)
        ;;   single-col UNIQUE     → :db.unique/value
        ;;     (Datahike enforces strict uniqueness natively; 23505
        ;;      falls out via :db.error/unique → errors.clj mapping.)
        ;;   multi-col  PRIMARY KEY / UNIQUE → additional :db.type/tuple
        ;;     attr with :db/tupleAttrs pointing at the components, same
        ;;     uniqueness as the single-col case.
        constraints (extract-ddl-constraints ct)
        pk-cols (:pk-cols constraints)
        constrained-vector-cols
        (set (concat pk-cols (mapcat :cols (:uniques constraints))))
        _vector-uniqueness
        (when (seq (set/intersection vector-columns constrained-vector-cols))
          (throw (errors/pg-error
                  :feature-not-supported
                  {:message (str "UNIQUE and PRIMARY KEY constraints on vector "
                                 "columns are not supported")})))
        single-pk? (= 1 (count pk-cols))
        single-pk-col (when single-pk? (first pk-cols))
        pk-cols-set (set pk-cols)
        ;; UNIQUE columns that aren't ALSO the single-col PK (avoid
        ;; double-constraining a single column — PG would reject the
        ;; redundant declaration, we silently dedupe).
        single-unique-cols (into #{}
                                 (comp (filter (comp #(= 1 (count %)) :cols))
                                       (map (comp first :cols))
                                       (remove pk-cols-set))
                                 (:uniques constraints))
        ;; Multi-col PK / UNIQUE — emit a derived tuple attr per
        ;; constraint. The ident name MUST NOT begin with '_' —
        ;; Datahike treats any name starting with underscore as a
        ;; reverse-ref shorthand (Datomic convention) and strips the
        ;; leading _ during attr validation, which then fails to
        ;; resolve. Using `pg$` as a prefix keeps the attrs
        ;; distinguishable from user columns without tripping that
        ;; detection.
        multi-pk-tuple (when (and (seq pk-cols) (> (count pk-cols) 1))
                         {:ident     (keyword ns "pg$pk_tuple")
                          :tuple-cols pk-cols
                          :unique    :db.unique/identity
                          :name      (or (:pk-name constraints)
                                         (str table-name "_pkey"))})
        multi-uniques (vec
                       (keep-indexed
                        (fn [i {:keys [cols name]}]
                          (when (> (count cols) 1)
                            {:ident     (keyword ns (str "pg$unique_tuple_" i))
                             :tuple-cols cols
                             :unique    :db.unique/value
                             :name      (or name
                                            (str table-name "_"
                                                 (str/join "_" cols) "_key"))}))
                        (:uniques constraints)))
        tuple-attrs (into (if multi-pk-tuple [multi-pk-tuple] [])
                          multi-uniques)
        ;; Allocate a stable PG OID for this table and attach it to the
        ;; row-marker entity. Used by pg_class.oid / pg_attribute.attrelid
        ;; so pgjdbc's field-metadata JOIN can resolve column names.
        ;; Persists with the schema (file-backed databases keep OIDs
        ;; across restarts; :memory dies with the db). Skip when the
        ;; row-marker already carries one — CREATE TABLE IF NOT EXISTS
        ;; re-runs the schema tx, and Datahike rejects changing a
        ;; cardinality/one attr that's already set on an entity.
        table-oid-val (when (and db (nil? (pgs/table-oid db table-name)))
                        (pgs/next-table-oid db))
        ;; Schema tx-data for columns
        schema-tx (into
                   [(cond-> {:db/ident       (pgs/row-marker-attr table-name)
                             :db/valueType   :db.type/boolean
                             :db/cardinality :db.cardinality/one}
                      table-oid-val (assoc :pg/table-oid table-oid-val))]
                   (for [^ColumnDefinition col columns
                         :let [col-name (params/unquote-ident (.getColumnName col))
                               ^ColDataType cdt (.getColDataType col)
                               raw-type-orig (types/normalize-sql-type-name
                                              (str (.getDataType cdt)))
                               ;; Strip schema prefix from type names. pg_dump
                               ;; emits `public.year`, `public.mpaa_rating` —
                               ;; we have a flat type namespace.
                               type-no-schema (last (str/split raw-type-orig #"\." 2))
                               ;; Check the enum registry first, then the
                               ;; domain registry. Either lowers to a
                               ;; concrete base type for the column.
                               q-fn d/q
                               enum-match (when db
                                            (ffirst (q-fn '{:find [?vs-ord]
                                                            :where [[?e :datahike.pg.enum/name ?n]
                                                                    [?e :datahike.pg.enum/values-ordered ?vs-ord]]
                                                            :in [$ ?n]}
                                                          db type-no-schema)))
                               ;; Query rather than a lookup-ref d/entity:
                               ;; :datahike.pg.domain/name isn't :db/unique,
                               ;; so a lookup ref makes datahike log an
                               ;; :error line for every non-domain type name
                               ;; (i.e. every ordinary CREATE TABLE column).
                               domain-match (when (and db (not enum-match)
                                                       (some? type-no-schema))
                                              (when-let [eid (ffirst
                                                              (q-fn '{:find [?e]
                                                                      :where [[?e :datahike.pg.domain/name ?n]]
                                                                      :in [$ ?n]}
                                                                    db type-no-schema))]
                                                (let [e (d/entity db eid)]
                                                  (when (:datahike.pg.domain/base-type e)
                                                    (into {} e)))))
                               ;; Resolved raw-type: enum → 'text', domain →
                               ;; its base-type + any args. Otherwise pass
                               ;; through.
                               raw-type (cond
                                          enum-match "text"
                                          domain-match
                                          (let [b (:datahike.pg.domain/base-type domain-match)
                                                args (some->> (:datahike.pg.domain/base-args domain-match)
                                                              seq (str/join ",") (#(str "(" % ")")))]
                                            (str b args))
                                          :else raw-type-orig)
                               base-type (str/replace raw-type #"\s*\([^)]*\)" "")
                               _ (when (types/unsupported-input-type? base-type)
                                   (throw (ex-info
                                           (str "type \"" base-type
                                                "\" is not supported until its PostgreSQL input parser is implemented")
                                           {:error :feature-not-supported
                                            :sqlstate "0A000"
                                            :type base-type})))
                               ;; Detect array column. JSqlParser exposes
                               ;; the array dimensions via getArrayData()
                               ;; — a list whose size = ndim (entries are
                               ;; null for unsized `[]`, integers for
                               ;; sized `[3]` which PG ignores anyway).
                               ;; We look up the element-keyword from
                               ;; `base-type` (typmod stripped) — which
                               ;; for `numeric(10,2)[]` resolves to
                               ;; `:numeric`, matching PG's array OIDs.
                               array-data (try (.getArrayData cdt)
                                               (catch Throwable _ nil))
                               ndim       (when (seq array-data) (count array-data))
                               array-spec (when ndim
                                            (when-let [elem (get types/sql-name->elem-kw base-type)]
                                              {:elem    elem
                                               :pg-name (str "_" (name elem))
                                               :ndim    ndim}))
                               ;; Array columns: store as serialized
                               ;; canonical text in :db.type/string.
                               ;; Round-trip via to-pg-text/from-pg-text.
                               dh-type (cond
                                         array-spec :db.type/string
                                         :else (or (get pg-type->dh-type raw-type)
                                                   (get pg-type->dh-type base-type)
                                                   :db.type/string))
                               ;; NUMERIC(p, s): preserve precision +
                               ;; scale via PG's atttypmod encoding so
                               ;; clients see the declared type. Real
                               ;; PG keeps these in pg_attribute; we
                               ;; tag the schema attr's ident entity
                               ;; with `:pg/typmod` and surface it in
                               ;; the catalog + describeResult. Skipped
                               ;; for array columns — we don't currently
                               ;; preserve element typmod through the
                               ;; serialized array codec.
                               numeric-typmod
                               (when (and (= dh-type :db.type/bigdec) (not array-spec))
                                 (let [[p s] (types/parse-numeric-args raw-type)]
                                   (when (or p s)
                                     (types/encode-numeric-typmod p s))))
                               ;; varchar(n) / char(n): the declared
                               ;; length was dropped entirely, so the
                               ;; column reported as plain `text` with no
                               ;; character_maximum_length and nothing
                               ;; enforced it on write. PostgreSQL's
                               ;; typmod for these is n + VARHDRSZ.
                               char-typmod
                               (when (and (= dh-type :db.type/string) (not array-spec))
                                 (when-let [n (types/parse-char-length raw-type)]
                                   (+ n 4)))
                               bit-typmod
                               (when (and (= dh-type :db.type/string) (not array-spec))
                                 ;; JSqlParser inconsistently includes the
                                 ;; modifier in getDataType for `bit(4)`, but
                                 ;; exposes `varbit(4)` as dataType="varbit"
                                 ;; plus a separate argument list. `str` on
                                 ;; ColDataType faithfully includes both.
                                 (some-> (types/parse-bit-length (str cdt)) long))
                               vector-typmod
                               (when (= dh-type :db.type/float-array)
                                 (pg-vector/parse-typmod
                                  (types/normalize-sql-type-name (str cdt))))
                               char-pg-type
                               (when-not array-spec
                                 (let [b (types/base-type-name-of raw-type)]
                                   (cond
                                     (contains? #{"char" "character" "bpchar"} b) "bpchar"
                                     (contains? #{"varchar" "character varying"} b) "varchar"
                                     (= "name" b) "name"
                                     :else nil)))
                               pk-here? (or (and single-pk-col (= col-name single-pk-col))
                                            (contains? pk-cols-set col-name))
                               ;; PRIMARY KEY is implicitly NOT NULL.  The SQL
                               ;; enforcement path reads only :pg/not-null;
                               ;; :db.unique/identity cannot represent that
                               ;; half of the PostgreSQL constraint by itself.
                               not-null-here? (or pk-here?
                                                  (column-is-not-null? col))
                               default-spec (let [spec (column-default-spec col)
                                                  bit-type? (contains?
                                                             #{"bit" "varbit" "bit varying"}
                                                             (types/base-type-name-of raw-type))]
                                              ;; A quoted unknown literal is
                                              ;; coerced to the declared bit
                                              ;; type at CREATE time in PG.
                                              ;; Preserve that intent: the
                                              ;; delayed default evaluator's
                                              ;; legacy :literal path parses
                                              ;; digit-only strings as longs.
                                              (if (and bit-type?
                                                       (= :literal (:kind spec))
                                                       (string? (:value spec)))
                                                (assoc spec :kind :bit-coerced)
                                                spec))
                               _ (when (= :unsupported (:kind default-spec))
                                   (throw (ex-info "DEFAULT expression not supported"
                                                   {:error :feature-not-supported
                                                    :feature (str "DEFAULT expression " (pr-str (:raw default-spec))
                                                                  " on column \"" col-name "\"")
                                                    :detail (str "DEFAULT expression " (pr-str (:raw default-spec))
                                                                 " on column \"" col-name "\" is not supported"
                                                                 " — only literals, now(), current_date,"
                                                                 " current_time, current_user, and"
                                                                 " nextval('seq') are implemented")
                                                    :column col-name})))]
                         :when (not (skip-col? col-name))]
                     (cond-> {:db/ident       (keyword ns col-name)
                              :db/valueType   dh-type
                              :db/cardinality :db.cardinality/one}
                       ;; Array column: tag with element-keyword and ndim
                       ;; so coerce-insert-value / value->string /
                       ;; coerce-pg-array can reconstruct the typed
                       ;; PgArray from the stored canonical text. The
                       ;; `:pg/type "_T"` slot drives column-OID
                       ;; resolution via pg-name->oid in oid_infer.
                       array-spec (assoc :pg/type        (:pg-name array-spec)
                                         :pg/array-elem  (:elem array-spec)
                                         ;; Long-cast for Datahike's
                                         ;; :db.type/long validation
                                         ;; (count returns int).
                                         :pg/array-ndim  (long (:ndim array-spec)))
                       numeric-typmod (assoc :pg/typmod numeric-typmod)
                       char-typmod (assoc :pg/typmod char-typmod)
                       bit-typmod (assoc :pg/typmod bit-typmod)
                       vector-typmod (assoc :pg/typmod vector-typmod)
                       (= dh-type :db.type/float-array) (assoc :pg/type "vector")
                       char-pg-type (assoc :pg/type char-pg-type)
                       not-null-here? (assoc :pg/not-null true)
                       (and default-spec
                            (not= :unsupported (:kind default-spec)))
                       (as-> m
                             (cond-> m
                               true (assoc :pg/default-kind (:kind default-spec))
                               (some? (:value default-spec))
                               (assoc :pg/default-value (str (:value default-spec)))
                               (= :nextval (:kind default-spec))
                               (assoc :pg/default-arg (:value default-spec))))
                       ;; Track original SQL type when the Datahike
                       ;; valueType isn't a 1:1 mapping. jsonb/json
                       ;; both reduce to :db.type/string; date/time/
                       ;; timestamp all collapse to :db.type/instant.
                       ;; Without this hint, ParameterDescription
                       ;; advertises a DATE param as `timestamp`
                       ;; (OID 1114) and pgjdbc rejects subsequent
                       ;; setDate binds with "Can't change resolved
                       ;; type for param …".
                       (and (not array-spec)
                            (#{"jsonb" "json" "money" "interval" "tsvector" "tsquery"
                               "date" "time" "timestamp"
                               "timestamptz" "timestamp without time zone"
                               "timestamp with time zone"
                               "time without time zone"
                               "time with time zone"} base-type))
                       (assoc :pg/type
                              (cond
                                (#{"timestamp without time zone"} base-type) "timestamp"
                                (#{"timestamp with time zone"} base-type)    "timestamptz"
                                (= "time without time zone" base-type) "time"
                                (= "time with time zone" base-type) "timetz"
                                :else base-type))

                       ;; bit / bit varying columns. Like jsonb they
                       ;; reduce to :db.type/string (the stored form is
                       ;; PG's own text output — the digit run), so the
                       ;; hint is what makes RowDescription report bit
                       ;; (1560) / varbit (1562) instead of text — see
                       ;; issue #28.
                       (and (not array-spec)
                            (#{:bit :varbit} (types/cast-category base-type)))
                       (assoc :pg/type
                              (if (= :varbit (types/cast-category base-type))
                                "varbit" "bit"))

                       ;; Narrow integer columns. Datahike stores every
                       ;; integer as :db.type/long, which would otherwise
                       ;; advertise int8 (OID 20) for a column the user
                       ;; declared `smallint`/`integer`. Record the width
                       ;; so RowDescription / ParameterDescription report
                       ;; int2 / int4 like PG — clients pick int4 vs int8
                       ;; parsers off the OID (node-postgres returns int8
                       ;; as a string, int4 as a number). bigint needs no
                       ;; hint: :db.type/long already → int8.
                       ;; Guard on (not array-spec): an `int[]` column has
                       ;; base-type "int" too, and already set :pg/type to
                       ;; its array name ("_int4") above — must not clobber.
                       (and (not array-spec)
                            (#{"smallint" "int2" "smallserial" "serial2"} base-type))
                       (assoc :pg/type "int2")
                       (and (not array-spec)
                            (#{"integer" "int" "int4" "serial" "serial4"} base-type))
                       (assoc :pg/type "int4")

                       ;; oid columns: stored as a long, but advertise the
                       ;; PG `oid` type (26) so clients parse it as a number
                       ;; rather than an int8 string.
                       (and (not array-spec) (= "oid" base-type))
                       (assoc :pg/type "oid")

                       ;; ENUM-typed column: remember the enum's name so
                       ;; the dump can re-emit the column as `<enum>`
                       ;; (not `text`). Membership constraints could be
                       ;; bolted on via `:pg/check-in` once the runtime
                       ;; CHECK enforcement lands; for now we only need
                       ;; to round-trip the type identity.
                       enum-match
                       (assoc :datahike.pg/enum-of type-no-schema)

                       ;; DOMAIN-typed column: remember the domain so the
                       ;; dump can emit `<domain>` instead of the lowered
                       ;; base type. The domain's CHECK clause lives on
                       ;; the registry entity and gets re-emitted as part
                       ;; of the CREATE DOMAIN block in the dump header.
                       domain-match
                       (assoc :datahike.pg/domain-of type-no-schema)
                       ;; Single-col PRIMARY KEY → upsert identity.
                       (and single-pk-col (= col-name single-pk-col))
                       (assoc :db/unique :db.unique/identity)
                       ;; Single-col UNIQUE (non-PK) → strict value.
                       (contains? single-unique-cols col-name)
                       (assoc :db/unique :db.unique/value))))
        ;; Derived tuple attrs for multi-col PK / UNIQUE constraints.
        tuple-schema-tx (mapv (fn [{:keys [ident tuple-cols unique]}]
                                {:db/ident       ident
                                 :db/valueType   :db.type/tuple
                                 :db/tupleAttrs  (mapv #(keyword ns %) tuple-cols)
                                 :db/cardinality :db.cardinality/one
                                 :db/unique      unique})
                              tuple-attrs)
        ;; Datahike tuple attributes implement composite SQL uniqueness,
        ;; but they are engine indexes rather than user columns. Hide them
        ;; from SELECT *, pg_attribute and information_schema while keeping
        ;; the underlying attribute available to Datahike.
        tuple-hint-tx (mapv (fn [{:keys [ident]}]
                              {:datahike.pg/for-ident ident
                               :datahike.pg/hidden true})
                            tuple-attrs)
        schema-tx (into schema-tx (into tuple-schema-tx tuple-hint-tx))
        ;; CHECK-constraint entities. One per CHECK clause, named
        ;; deterministically so CREATE TABLE IF NOT EXISTS is
        ;; idempotent (:pg/check-name carries :db.unique/identity).
        check-entities
        (vec (for [[i {:keys [name col expr]}] (map-indexed vector (:checks constraints))
                   :let [cname (or name
                                   (if col
                                     (str table-name "_" col "_check")
                                     (str table-name "_check_" i)))]]
               {:pg/check-name  cname
                :pg/check-table table-name
                :pg/check-expr  expr}))
        child-schema-by-col
        (into {}
              (keep (fn [datum]
                      (when-let [ident (and (map? datum) (:db/ident datum))]
                        (when (= table-name (namespace ident))
                          [(name ident) datum]))))
              schema-tx)
        ;; FK-constraint entities. Column lists stored as
        ;; JSON-serialized strings for order-preserving round-trip.
        fk-entities
        (vec (for [[i {:keys [name cols parent-table parent-cols on-delete on-update]}]
                   (map-indexed vector (:fks constraints))
                   :let [cname (or name
                                   (str table-name "_"
                                        (str/join "_" cols) "_fkey"))
                         ;; SQL's omitted referenced-column list means the
                         ;; parent's PRIMARY KEY, not an empty tuple.  Keeping
                         ;; it empty made every inline `REFERENCES parent`
                         ;; check vacuous and was particularly visible in the
                         ;; upstream enum regression test.
                         parent-cols (if (seq parent-cols)
                                       parent-cols
                                       (or (primary-key-cols db parent-table)
                                           (throw
                                            (ex-info
                                             (str "there is no primary key for referenced table \""
                                                  parent-table "\"")
                                             {:sqlstate "42830"
                                              :constraint cname
                                              :table parent-table}))))
                         _ (when-not (= (count cols) (count parent-cols))
                             (throw
                              (ex-info "number of referencing and referenced columns disagree"
                                       {:sqlstate "42830"
                                        :constraint cname
                                        :table table-name})))
                         ;; Enum equality is nominal: two enums with the same
                         ;; string carrier (or even identical labels) remain
                         ;; incompatible PostgreSQL types.  Validate their
                         ;; identity at DDL time before the storage lowering
                         ;; to :db.type/string erases that distinction.
                         _ (doseq [[child-col parent-col]
                                   (map vector cols parent-cols)
                                   :let [child-enum
                                         (:datahike.pg/enum-of
                                          (get child-schema-by-col child-col))
                                         parent-enum
                                         (attr-enum-name
                                          db (keyword parent-table parent-col))]
                                   :when (and (or child-enum parent-enum)
                                              (not= child-enum parent-enum))]
                             (throw
                              (ex-info
                               (str "foreign key constraint \"" cname
                                    "\" cannot be implemented")
                               {:sqlstate "42804"
                                :constraint cname
                                :table table-name
                                :detail
                                (str "Key columns \"" child-col
                                     "\" of the referencing table and \""
                                     parent-col
                                     "\" of the referenced table are of incompatible types: "
                                     (or child-enum "non-enum") " and "
                                     (or parent-enum "non-enum") ".")})))
                         ->action (fn [s]
                                    (when s
                                      (case (str/lower-case s)
                                        "cascade"     :cascade
                                        "set null"    :set-null
                                        "set default" :set-default
                                        "restrict"    :restrict
                                        "no action"   :no-action
                                        :no-action)))
                         od (->action on-delete)
                         ou (->action on-update)]
                   :when parent-table]
               (cond-> {:pg/fk-name         cname
                        :pg/fk-child-table  table-name
                        :pg/fk-child-cols   (jb/serialize-jsonb cols)
                        :pg/fk-parent-table parent-table
                        :pg/fk-parent-cols  (jb/serialize-jsonb parent-cols)}
                 od (assoc :pg/fk-on-delete od)
                 ou (assoc :pg/fk-on-update ou))))
        schema-tx (into schema-tx (into check-entities fk-entities))
        ;; Loud error at DDL for FK actions we don't yet implement.
        ;; ON DELETE CASCADE *is* implemented (server.clj
        ;; collect-fk-cascade-retractions!) so we accept it here.
        ;; ON DELETE SET NULL / SET DEFAULT and ON UPDATE * still raise.
        _ (doseq [fk fk-entities]
            (when (contains? #{:set-null :set-default}
                             (:pg/fk-on-delete fk))
              (throw (ex-info "ON DELETE action not supported"
                              {:error :feature-not-supported
                               :feature (str "FOREIGN KEY ON DELETE "
                                             (name (:pg/fk-on-delete fk)))
                               :detail (str "FOREIGN KEY ON DELETE "
                                            (name (:pg/fk-on-delete fk))
                                            " is not yet supported for "
                                            (:pg/fk-name fk)
                                            " — only NO ACTION / RESTRICT / CASCADE are enforced")
                               :constraint (:pg/fk-name fk)})))
            (when (contains? #{:cascade :set-null :set-default}
                             (:pg/fk-on-update fk))
              (throw (ex-info "ON UPDATE action not supported"
                              {:error :feature-not-supported
                               :feature (str "FOREIGN KEY ON UPDATE "
                                             (name (:pg/fk-on-update fk)))
                               :detail (str "FOREIGN KEY ON UPDATE "
                                            (name (:pg/fk-on-update fk))
                                            " is not yet supported for "
                                            (:pg/fk-name fk))
                               :constraint (:pg/fk-name fk)}))))
        ;; Sequence schema + initial entity for each IDENTITY column
        seq-tx (vec (mapcat (fn [col-name]
                              (let [seq-name (str table-name "_" col-name "_seq")]
                                [{:db/ident :__seq__/name :db/valueType :db.type/string
                                  :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
                                 {:db/ident :__seq__/value :db/valueType :db.type/long
                                  :db/cardinality :db.cardinality/one}
                                 {:db/ident :__seq__/increment :db/valueType :db.type/long
                                  :db/cardinality :db.cardinality/one}
                                 {:__seq__/name seq-name :__seq__/value 0 :__seq__/increment 1}]))
                            identity-cols))]
    (cond-> {:type :ddl-create
             :table-name table-name
             :temp? temp?
             :if-not-exists? (.isIfNotExists ct)
             :column-order col-names
             :identity-cols identity-cols
             :pk-cols pk-cols
             :pk-name (or (:pk-name constraints)
                          (when (seq pk-cols) (str table-name "_pkey")))
             :unique-cols (vec single-unique-cols)
             :tx-data (into schema-tx seq-tx)}
      parent-table (assoc :inherits parent-table))))

;; ============================================================================
;; Sequence DDL translation
;; ============================================================================

(def ^:private seq-type-bounds
  "PG's per-type sequence bounds (sequence.c:1454, :1486). The default
   type is bigint."
  {"smallint" [-32768 32767]
   "int2"     [-32768 32767]
   "integer"  [-2147483648 2147483647]
   "int"      [-2147483648 2147483647]
   "int4"     [-2147483648 2147483647]
   "bigint"   [-9223372036854775808 9223372036854775807]
   "int8"     [-9223372036854775808 9223372036854775807]})

(defn- seq-invalid [detail]
  (throw (errors/pg-error :invalid-parameter-value {:detail detail})))

(defn- seq-syntax [detail]
  (throw (errors/pg-error :syntax-error {:detail detail})))

(defn sequence-params
  "Resolve a classifier option list into concrete sequence parameters,
   applying PG's defaults and raising PG's errors.

   Mirrors `init_params` (postgres src/backend/commands/sequence.c:1260)
   including its ORDER, because a statement with more than one problem
   must report the same one PG reports: duplicate detection, then AS,
   INCREMENT, CYCLE, MAXVALUE, MINVALUE, the min/max crosscheck, START,
   RESTART, CACHE.

   `existing` is the current parameter map for ALTER (nil for CREATE);
   options left unspecified keep their existing values on ALTER and take
   the defaults on CREATE.

   Returns {:type :increment :minvalue :maxvalue :start :cache :cycle?
            :restart :owned-by}."
  [opts {:keys [existing]}]
  ;; Duplicate/conflicting options — 42601, before anything is read.
  ;; NO MINVALUE and MINVALUE n are the same option, so `MINVALUE 5 NO
  ;; MINVALUE` collides here, as does CYCLE with NO CYCLE.
  (let [names (map first opts)]
    (when-let [dup (some (fn [[k n]] (when (> n 1) k)) (frequencies names))]
      (when (contains? #{:as :cache :cycle :increment :maxvalue :minvalue
                         :owned-by :restart :start}
                       dup)
        (seq-syntax "conflicting or redundant options"))))

  (let [o (into {} opts)
        init? (nil? existing)]

    ;; Options PG parses but refuses in this position.
    (when (contains? o :sequence-name)
      (seq-syntax "invalid sequence option SEQUENCE NAME"))
    (when (or (contains? o :logged) (contains? o :unlogged))
      ;; PG reaches this through a bare elog, so it really is XX000
      ;; upstream rather than a user-facing error class.
      (throw (ex-info (str "option \""
                           (if (contains? o :logged) "logged" "unlogged")
                           "\" not recognized")
                      {:sqlstate "XX000"})))

    (let [;; --- AS <type>
          type-name (or (:as o) (:type existing) "bigint")
          [type-min type-max]
          (or (seq-type-bounds type-name)
              (seq-invalid "sequence type must be smallint, integer, or bigint"))

          ;; --- INCREMENT
          increment (cond
                      (contains? o :increment) (:increment o)
                      existing (:increment existing)
                      :else 1)
          _ (when (zero? increment) (seq-invalid "INCREMENT must not be zero"))
          ascending? (pos? increment)

          ;; --- CYCLE
          cycle? (cond
                   (contains? o :cycle) (:cycle o)
                   existing (:cycle? existing)
                   :else false)

          ;; --- MAXVALUE. `NO MAXVALUE` (:none) means "the default for
          ;; this type and increment sign", NOT unbounded.
          maxvalue (let [v (:maxvalue o)]
                     (cond
                       (and (some? v) (not= v :none)) v
                       (or (= v :none) init?) (if ascending? type-max -1)
                       :else (:maxvalue existing)))
          _ (when (or (< maxvalue type-min) (> maxvalue type-max))
              (seq-invalid (str "MAXVALUE (" maxvalue ") is out of range for "
                                "sequence data type " type-name)))

          ;; --- MINVALUE
          minvalue (let [v (:minvalue o)]
                     (cond
                       (and (some? v) (not= v :none)) v
                       (or (= v :none) init?) (if ascending? 1 type-min)
                       :else (:minvalue existing)))
          _ (when (or (< minvalue type-min) (> minvalue type-max))
              (seq-invalid (str "MINVALUE (" minvalue ") is out of range for "
                                "sequence data type " type-name)))

          ;; PG compares with >=, so min == max is rejected even though
          ;; the message says "must be less than".
          _ (when (>= minvalue maxvalue)
              (seq-invalid (str "MINVALUE (" minvalue ") must be less than "
                                "MAXVALUE (" maxvalue ")")))

          ;; --- START
          start (cond
                  (contains? o :start) (:start o)
                  existing (:start existing)
                  :else (if ascending? minvalue maxvalue))
          _ (when (< start minvalue)
              (seq-invalid (str "START value (" start ") cannot be less than "
                                "MINVALUE (" minvalue ")")))
          _ (when (> start maxvalue)
              (seq-invalid (str "START value (" start ") cannot be greater than "
                                "MAXVALUE (" maxvalue ")")))

          ;; --- RESTART. A bare RESTART (:default) restarts at START —
          ;; the START of this same statement, since START is applied
          ;; first. RESTART never changes START itself.
          restart (when (contains? o :restart)
                    (let [v (:restart o)]
                      (if (= v :default) start v)))
          _ (when restart
              (when (< restart minvalue)
                (seq-invalid (str "RESTART value (" restart ") cannot be less than "
                                  "MINVALUE (" minvalue ")")))
              (when (> restart maxvalue)
                (seq-invalid (str "RESTART value (" restart ") cannot be greater than "
                                  "MAXVALUE (" maxvalue ")"))))

          ;; --- CACHE
          cache (cond
                  (contains? o :cache) (:cache o)
                  existing (:cache existing)
                  :else 1)
          _ (when (<= cache 0)
              (seq-invalid (str "CACHE (" cache ") must be greater than zero")))]
      {:type type-name
       :increment increment
       :minvalue minvalue
       :maxvalue maxvalue
       :start start
       :cache cache
       :cycle? cycle?
       :restart restart
       :owned-by (:owned-by o)})))

(def sequence-schema
  "Schema attributes backing a sequence entity. Idempotent — re-transacted
   on every CREATE SEQUENCE."
  [{:db/ident :__seq__/name :db/valueType :db.type/string
    :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :__seq__/value :db/valueType :db.type/long
    :db/cardinality :db.cardinality/one}
   {:db/ident :__seq__/increment :db/valueType :db.type/long
    :db/cardinality :db.cardinality/one}
   {:db/ident :__seq__/minvalue :db/valueType :db.type/long
    :db/cardinality :db.cardinality/one}
   {:db/ident :__seq__/maxvalue :db/valueType :db.type/long
    :db/cardinality :db.cardinality/one}
   {:db/ident :__seq__/cache :db/valueType :db.type/long
    :db/cardinality :db.cardinality/one}
   {:db/ident :__seq__/cycle :db/valueType :db.type/boolean
    :db/cardinality :db.cardinality/one}
   {:db/ident :__seq__/start :db/valueType :db.type/long
    :db/cardinality :db.cardinality/one}
   {:db/ident :__seq__/type :db/valueType :db.type/string
    :db/cardinality :db.cardinality/one}])

(defn sequence-entity
  "The stored entity for a sequence with the given resolved params.

   `:__seq__/value` holds the last value HANDED OUT, so a fresh sequence
   stores `start - increment` and the first advance lands exactly on
   start. (PG models this as last_value + is_called=false; the offset
   encoding is equivalent for a single-value-at-a-time nextval and is
   what the IDENTITY path in translate-create-table already assumes.)"
  [seq-name {:keys [increment minvalue maxvalue start cache cycle? type]}]
  {:__seq__/name seq-name
   :__seq__/value (- start increment)
   :__seq__/increment increment
   :__seq__/minvalue minvalue
   :__seq__/maxvalue maxvalue
   :__seq__/cache cache
   :__seq__/cycle cycle?
   :__seq__/start start
   :__seq__/type type})

(defn translate-create-sequence
  "Translate a classified CREATE SEQUENCE into schema + initial entity.

   Consumes the token classifier's `:seq-opts` rather than JSqlParser's
   AST: the grammar there covers only a subset of PG's option list, and
   the values used to be recovered by regex over the re-rendered SQL
   (`increment\\s+by\\s+(\\d+)`), which could not see a negative increment
   and silently dropped MINVALUE/MAXVALUE/CACHE/CYCLE. See issue #21."
  [{:keys [seq-name seq-opts if-not-exists?]}]
  (let [params (sequence-params seq-opts {})]
    {:type :ddl-create-sequence
     :seq-name seq-name
     :if-not-exists? if-not-exists?
     :seq-params params
     :tx-data (conj (vec sequence-schema) (sequence-entity seq-name params))}))
