#!/usr/bin/env bash
# Idempotent setup for the pgjdbc conformance suite.
#
# What it does:
#   1. Verifies that git and a Java >= 17 JDK are available.
#   2. Clones pgjdbc at a known-good stable tag (REL42.7.5) into ./pgjdbc/
#      if it is not already there. Second runs are a no-op.
#   3. Writes build.local.properties pointing at the Datahike pgwire server
#      (localhost:15432, user=datahike, db=datahike, any password).
#
# This script does NOT start the pgwire server and does NOT run the tests.
# Use run.sh for that after you have started the server:
#
#   cd $DATAHIKE && DATAHIKE_QUERY_PLANNER=true \
#     clojure -A:test -M test/integration/start_pgwire.clj
#
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_URL="https://github.com/pgjdbc/pgjdbc.git"
REPO_TAG="REL42.7.5"
CLONE_DIR="${HERE}/pgjdbc"

# ---- dependency check -------------------------------------------------------

have() { command -v "$1" >/dev/null 2>&1; }

require() {
  if ! have "$1"; then
    echo "ERROR: required tool '$1' not found on PATH." >&2
    echo "       Install it and re-run setup.sh; this script does not install tools." >&2
    exit 2
  fi
}

require git
require java

# pgjdbc 42.7.x requires Java >= 17 to *build*; Java 17 or 21 is recommended.
JAVA_MAJOR="$(java -version 2>&1 | awk -F '[".]' '/version/ {print $2; exit}')"
if [[ -z "${JAVA_MAJOR}" || "${JAVA_MAJOR}" -lt 17 ]]; then
  echo "ERROR: pgjdbc requires Java >= 17 to build (detected: ${JAVA_MAJOR:-unknown})." >&2
  echo "       Set JAVA_HOME to a JDK 17 or 21 install." >&2
  exit 2
fi

# ---- clone ------------------------------------------------------------------

if [[ -d "${CLONE_DIR}/.git" ]]; then
  echo "[setup] pgjdbc already cloned at ${CLONE_DIR} (tag: $(git -C "${CLONE_DIR}" describe --tags --always 2>/dev/null || echo '?'))"
else
  echo "[setup] cloning pgjdbc ${REPO_TAG} into ${CLONE_DIR}"
  git clone --depth=1 --branch="${REPO_TAG}" "${REPO_URL}" "${CLONE_DIR}"
fi

# ---- local properties -------------------------------------------------------

# pgjdbc reads $JDBC_SRC/build.local.properties to override build.properties.
# We point every property at our pgwire server. The "privilegedUser" setting
# is required by some DDL-heavy tests; we use the same account because Datahike
# has no role system.
PROPS="${CLONE_DIR}/build.local.properties"
cat > "${PROPS}" <<'EOF'
# Generated by datahike/test/integration/pgjdbc/setup.sh
# Target: datahike pgwire server on localhost:15432
server=localhost
port=15432
database=datahike
username=datahike
password=datahike
privilegedUser=datahike
privilegedPassword=datahike
# Disable SSL and SCRAM - datahike pgwire does not implement them.
ssl=false
sslmode=disable
# We run against a single logical instance; replication-dependent tests are
# excluded by run.sh, but set wal_level-sensitive flags conservatively anyway.
preparethreshold=1
protocolVersion=3
EOF

echo "[setup] wrote ${PROPS}"
echo "[setup] done. Start the pgwire server, then run:  ./run.sh"
